/**
 * Wave T budget: files that still set raw text sizes.
 *
 * The number is how many raw-size occurrences that file is still allowed —
 * `fontSize: <n>`, `text-[<n>px]`, or a bare `text-xs`…`text-6xl`. The gate in
 * typeScaleLint.test.ts is "no NEW violations": a file may drop below its
 * budget (tighten the number when you do), never rise above it, and a file not
 * listed here must have none at all.
 *
 * Migrating a file means deleting its row, not editing the count down to zero.
 * The six steps live in typeScale.ts; StyleSheet screens use `<T.Body>` from
 * components/ui, class-based screens use `text-body`.
 *
 * Seeded 2026-09-06 from the tree as it stood after the Wave T chrome, Library,
 * Tests, Me and chart migrations: 206 files, 2260 occurrences. Wave V1 polish
 * then dropped the two rows whose files no longer set any raw size —
 * StudyHubScreen.tsx and CourseReadinessCard.tsx, 5 each — leaving 200 rows
 * and a 2154 budget against 2147 actual.
 */
export const TYPE_SCALE_ALLOWLIST: Record<string, number> = {
  'src/components/AICompanionPanel.tsx': 17,
  'src/components/AIDisclaimer.tsx': 2,
  'src/components/AIExplainModal.tsx': 10,
  'src/components/AIGenerateFlashcardsModal.tsx': 16,
  'src/components/AIGenerateQuestionsModal.tsx': 15,
  'src/components/AITutorModal.tsx': 6,
  'src/components/AIUsageBadge.tsx': 11,
  'src/components/AccountLifecycleModals.tsx': 14,
  'src/components/AddMembersModal.tsx': 13,
  'src/components/ChallengeModal.tsx': 11,
  'src/components/CollaboratorsModal.tsx': 7,
  'src/components/CollapsibleSection.tsx': 2,
  'src/components/ContactSupportModal.tsx': 7,
  'src/components/CookieNoticeBanner.tsx': 14,
  'src/components/CoursePicker.tsx': 11,
  'src/components/CreateFlashcardModal.tsx': 18,
  'src/components/DailyGoalsProgress.tsx': 4,
  'src/components/DailyQuestsWidget.tsx': 7,
  'src/components/DailyQuizWidget.tsx': 12,
  'src/components/ErrorBoundary.tsx': 3,
  'src/components/GroupInfoModal.tsx': 19,
  'src/components/GroupInviteLinkPanel.tsx': 4,
  'src/components/ImportAndStudyModal.tsx': 12,
  'src/components/LectureRecordingBanner.tsx': 5,
  'src/components/NewDirectMessageModal.tsx': 8,
  'src/components/NoteCollaboratorsModal.tsx': 16,
  'src/components/NoteImageGallery.tsx': 4,
  'src/components/NotePdfViewer.tsx': 10,
  'src/components/OcclusionEditor.tsx': 5,
  'src/components/QuestionModal.tsx': 15,
  'src/components/RequestError.tsx': 7,
  'src/components/SwipeableFlashcard.tsx': 7,
  'src/components/SyncStatusIndicator.tsx': 5,
  'src/components/TestAnalysisContent.tsx': 21,
  'src/components/TestConfigModal.styles.ts': 26,
  'src/components/TestConfigModal.tsx': 1,
  'src/components/ThemedComponents.tsx': 2,
  'src/components/TopicPicker.tsx': 9,
  'src/components/UsernameRequiredModal.tsx': 12,
  'src/components/academic/CourseMultiSelect.tsx': 8,
  'src/components/academic/SemesterPicker.tsx': 1,
  'src/components/academic/StudyLevelPicker.tsx': 1,
  'src/components/auth/ResendEmailButton.tsx': 1,
  'src/components/auth/SocialAuthButtons.tsx': 2,
  'src/components/board/BoardActionRow.tsx': 1,
  'src/components/board/BoardComposer.tsx': 6,
  'src/components/board/BoardImage.tsx': 1,
  'src/components/board/BoardPostCard.tsx': 8,
  'src/components/board/BoardQuotedPost.tsx': 7,
  'src/components/board/BoardRepostSheet.tsx': 8,
  'src/components/board/LegacyQuestionCard.tsx': 5,
  'src/components/board/PinnedBanner.tsx': 3,
  'src/components/budget/BudgetDatePicker.tsx': 6,
  'src/components/chat/ChatComposer.tsx': 6,
  'src/components/chat/ChatMessageBody.tsx': 3,
  'src/components/chat/ChatThreadModal.tsx': 4,
  'src/components/chat/ChatWallpaper.tsx': 1,
  'src/components/chat/DmBubble.tsx': 6,
  'src/components/chat/DmOffersPanel.tsx': 17,
  'src/components/chat/ForwardMessageSheet.tsx': 5,
  'src/components/chat/GroupChatHeader.tsx': 10,
  'src/components/chat/MessageBubble.tsx': 13,
  'src/components/chat/MessageReactions.tsx': 3,
  'src/components/chat/QuestionVoteBar.tsx': 4,
  'src/components/chat/VoiceNotePlayer.tsx': 4,
  'src/components/community/ChannelRow.tsx': 3,
  'src/components/community/MemberRow.tsx': 2,
  'src/components/community/RoomRow.tsx': 3,
  'src/components/community/StudyGroupRow.tsx': 2,
  'src/components/dashboard/AIStudyCoachCard.tsx': 9,
  'src/components/dashboard/DashboardHeroCard.tsx': 9,
  'src/components/dashboard/DashboardInsights.tsx': 7,
  'src/components/dashboard/DashboardQuickLinks.tsx': 1,
  'src/components/featureTips/FeatureTipSheet.tsx': 5,
  'src/components/jobs/InterviewCalendarActions.tsx': 1,
  'src/components/jobs/JobApplicantNotes.tsx': 9,
  'src/components/jobs/JobBulkActionsBar.tsx': 7,
  'src/components/jobs/JobEmployerInsights.tsx': 13,
  'src/components/jobs/JobHiringFunnelStrip.tsx': 2,
  'src/components/jobs/JobInterviewInvite.tsx': 10,
  'src/components/jobs/JobInterviewScheduler.tsx': 25,
  'src/components/jobs/JobMessageTemplatePicker.tsx': 1,
  'src/components/jobs/JobOfferCard.tsx': 15,
  'src/components/jobs/JobOfferPanel.tsx': 27,
  'src/components/jobs/JobPostingInsights.tsx': 6,
  'src/components/jobs/ResumeUploadField.tsx': 8,
  'src/components/layout/TopBar.tsx': 1,
  'src/components/library/LibraryCourseTree.tsx': 16,
  'src/components/library/LibrarySearchResults.tsx': 7,
  'src/components/library/ManageOutlineSheet.tsx': 8,
  'src/components/moderation/AccountSuspendedBanner.tsx': 3,
  'src/components/moderation/ListingTakedownNotice.tsx': 14,
  'src/components/moderation/ReportContentSheet.tsx': 10,
  'src/components/moderation/RightsAttestationCheckbox.tsx': 3,
  'src/screens/auth/ForgotPasswordScreen.tsx': 4,
  'src/screens/auth/LoginScreen.tsx': 5,
  'src/screens/auth/ResetPasswordScreen.tsx': 5,
  'src/screens/auth/SignUpScreen.tsx': 14,
  'src/screens/auth/VerifyEmailScreen.tsx': 4,
  'src/screens/budget/AddExpenseScreen.tsx': 10,
  'src/screens/budget/AddIncomeScreen.tsx': 10,
  'src/screens/budget/AddInvestmentScreen.tsx': 5,
  'src/screens/budget/BudgetScreen.tsx': 38,
  'src/screens/budget/ExpenseSplitScreen.tsx': 16,
  'src/screens/budget/FinancialToolkitScreen.tsx': 16,
  'src/screens/budget/RecurringScreen.tsx': 8,
  'src/screens/budget/SavingsGoalsScreen.tsx': 8,
  'src/screens/budget/SetBudgetScreen.tsx': 17,
  'src/screens/budget/SetCategoryBudgetScreen.tsx': 2,
  'src/screens/budget/StudyWalletPanel.tsx': 7,
  'src/screens/dashboard/LeaderboardScreen.tsx': 6,
  'src/screens/discover/CommunityBoardScreen.tsx': 8,
  'src/screens/discover/CommunityMembersScreen.tsx': 6,
  'src/screens/discover/CommunityPostScreen.tsx': 12,
  'src/screens/discover/DiscoverComingSoon.tsx': 3,
  'src/screens/discover/DiscoverScreen.tsx': 32,
  'src/screens/discover/DiscoverWorkspaceBar.tsx': 1,
  'src/screens/discover/FeedScreen.tsx': 5,
  'src/screens/discover/GroupDiscoverabilityFields.tsx': 6,
  'src/screens/discover/MasteryScreen.tsx': 16,
  'src/screens/discover/SavedPostsScreen.tsx': 7,
  'src/screens/flashcards/CramSessionScreen.tsx': 10,
  'src/screens/flashcards/DeckDetailScreen.tsx': 25,
  'src/screens/flashcards/FlashcardReviewScreen.tsx': 16,
  'src/screens/flashcards/FlashcardsScreen.tsx': 14,
  'src/screens/flashcards/LearnStudyScreen.tsx': 8,
  'src/screens/flashcards/MatchStudyScreen.tsx': 7,
  'src/screens/games/ChallengesInboxScreen.tsx': 4,
  'src/screens/games/GameResultScreen.tsx': 9,
  'src/screens/games/GameScreen.tsx': 16,
  'src/screens/groups/CreateGroupScreen.tsx': 11,
  'src/screens/groups/DirectMessageScreen.tsx': 27,
  'src/screens/groups/GroupChatScreen.tsx': 17,
  'src/screens/groups/GroupsScreen.tsx': 15,
  'src/screens/legal/LegalDocumentScreen.tsx': 2,
  'src/screens/library/LibraryScreen.tsx': 1,
  'src/screens/marketplace/CampusPicker.tsx': 6,
  'src/screens/marketplace/CourseBrowseScreen.tsx': 9,
  'src/screens/marketplace/CourseListingsScreen.tsx': 11,
  'src/screens/marketplace/CreateJobScreen.tsx': 29,
  'src/screens/marketplace/CreateListingScreen.tsx': 25,
  'src/screens/marketplace/CreatorProfileScreen.tsx': 14,
  'src/screens/marketplace/EditListingScreen.tsx': 23,
  'src/screens/marketplace/FavoritesScreen.tsx': 4,
  'src/screens/marketplace/InquiriesScreen.tsx': 7,
  'src/screens/marketplace/JobApplicantsScreen.tsx': 20,
  'src/screens/marketplace/JobCompanyScreen.tsx': 12,
  'src/screens/marketplace/JobDetailScreen.tsx': 40,
  'src/screens/marketplace/JobEmployerScreen.tsx': 29,
  'src/screens/marketplace/JobsHomeScreen.tsx': 40,
  'src/screens/marketplace/ListingClassifier.tsx': 14,
  'src/screens/marketplace/ListingDetailScreen.tsx': 66,
  'src/screens/marketplace/MakeOfferScreen.tsx': 8,
  'src/screens/marketplace/MarketplaceScreen.tsx': 51,
  'src/screens/marketplace/MyJobApplicationsScreen.tsx': 29,
  'src/screens/marketplace/MyJobPostingsScreen.tsx': 26,
  'src/screens/marketplace/MyListingsScreen.tsx': 11,
  'src/screens/marketplace/OffersScreen.tsx': 8,
  'src/screens/marketplace/OpenDisputeModal.tsx': 9,
  'src/screens/marketplace/OrderDetailScreen.tsx': 14,
  'src/screens/marketplace/OrdersScreen.tsx': 2,
  'src/screens/marketplace/PurchasesScreen.tsx': 11,
  'src/screens/marketplace/SellerCustomersScreen.tsx': 9,
  'src/screens/marketplace/SellerPayoutScreen.tsx': 17,
  'src/screens/marketplace/SellerPayoutSetup.tsx': 7,
  'src/screens/marketplace/SellerProfileScreen.tsx': 19,
  'src/screens/marketplace/SemesterProductsScreen.tsx': 8,
  'src/screens/marketplace/ShopAccountScreen.tsx': 6,
  'src/screens/marketplace/ShopBrowseScreen.tsx': 7,
  'src/screens/marketplace/StudyProductDraftsScreen.tsx': 9,
  'src/screens/marketplace/components/OrderStatusPill.tsx': 1,
  'src/screens/marketplace/components/SellerNeedsYouStrip.tsx': 5,
  'src/screens/marketplace/components/SellerToolsRow.tsx': 2,
  'src/screens/marketplace/components/ShopQuickActions.tsx': 1,
  'src/screens/marketplace/modals/CreateBundleModal.tsx': 6,
  'src/screens/marketplace/modals/SellerCampaignModal.tsx': 5,
  'src/screens/marketplace/modals/SellerCouponsModal.tsx': 6,
  'src/screens/marketplace/modals/SellerInsightsModal.tsx': 21,
  'src/screens/marketplace/modals/SellerOnboardingModal.tsx': 4,
  'src/screens/notes/NoteEditorScreen.tsx': 24,
  'src/screens/notes/NoteShareAcceptScreen.tsx': 5,
  'src/screens/onboarding/OnboardingScreen.tsx': 7,
  'src/screens/settings/AcademicSettingsScreen.tsx': 11,
  'src/screens/settings/BlockedUsersScreen.tsx': 7,
  'src/screens/settings/EditProfileScreen.tsx': 7,
  'src/screens/settings/InviteFriendsScreen.tsx': 11,
  'src/screens/settings/NotificationsScreen.tsx': 4,
  'src/screens/settings/OfflineScreen.tsx': 27,
  'src/screens/settings/PublishQuestionBankModal.tsx': 22,
  'src/screens/settings/PublishStudyPackModal.tsx': 21,
  'src/screens/settings/SettingsScreen.tsx': 21,
  'src/screens/study/StudyRoomScreen.tsx': 10,
  'src/screens/tests/TestAnalysisScreen.tsx': 4,
  'src/screens/tests/TestTakingScreen.styles.ts': 43,
  'src/screens/tests/TestTakingScreen.tsx': 1,
};

/** Total budget across the tree — the number Wave T+1 has to bring down. */
export const TYPE_SCALE_ALLOWLIST_TOTAL = Object.values(TYPE_SCALE_ALLOWLIST).reduce(
  (a, b) => a + b,
  0
);
