export interface MarketplaceCampus {
  id: string;
  name: string;
  city: string;
  state: string;
  country_code: string;
  slug: string;
}

/** Special campus for free-text city when the user's school/city is not listed. */
export const OTHER_CITY_CAMPUS_SLUG = 'other-city-nigeria';

/** Seed campuses for Nigeria — synced with DB migration (NUC federal/state/private + polytechnics + city Others). */
export const NIGERIA_MARKETPLACE_CAMPUSES: Omit<MarketplaceCampus, 'id'>[] = [
  { name: "Abubakar Tafawa Balewa University", city: "Bauchi", state: "Bauchi", country_code: 'NG', slug: "abubakar-tafawa-balewa-university" },
  { name: "Ahmadu Bello University", city: "Zaria", state: "Kaduna", country_code: 'NG', slug: "ahmadu-bello-university" },
  { name: "Bayero University", city: "Kano", state: "Kano", country_code: 'NG', slug: "bayero-university" },
  { name: "Federal University Gashua", city: "Gashua", state: "Yobe", country_code: 'NG', slug: "federal-university-gashua" },
  { name: "Federal University of Petroleum Resources", city: "Effurun", state: "Delta", country_code: 'NG', slug: "federal-university-of-petroleum-resources" },
  { name: "Federal University of Technology, Akure", city: "Akure", state: "Ondo", country_code: 'NG', slug: "federal-university-of-technology-akure" },
  { name: "Federal University of Technology, Minna", city: "Minna", state: "Niger", country_code: 'NG', slug: "federal-university-of-technology-minna" },
  { name: "Federal University of Technology, Owerri", city: "Owerri", state: "Imo", country_code: 'NG', slug: "federal-university-of-technology-owerri" },
  { name: "Federal University Dutse", city: "Dutse", state: "Jigawa", country_code: 'NG', slug: "federal-university-dutse" },
  { name: "Federal University Dutsin-Ma", city: "Dutsin-Ma", state: "Katsina", country_code: 'NG', slug: "federal-university-dutsin-ma" },
  { name: "Federal University Kashere", city: "Kashere", state: "Gombe", country_code: 'NG', slug: "federal-university-kashere" },
  { name: "Federal University Lafia", city: "Lafia", state: "Nasarawa", country_code: 'NG', slug: "federal-university-lafia" },
  { name: "Federal University Lokoja", city: "Lokoja", state: "Kogi", country_code: 'NG', slug: "federal-university-lokoja" },
  { name: "Alex Ekwueme Federal University Ndufu-Alike", city: "Ndufu-Alike", state: "Ebonyi", country_code: 'NG', slug: "alex-ekwueme-federal-university-ndufu-alike" },
  { name: "Federal University Otuoke", city: "Otuoke", state: "Bayelsa", country_code: 'NG', slug: "federal-university-otuoke" },
  { name: "Federal University Oye-Ekiti", city: "Oye-Ekiti", state: "Ekiti", country_code: 'NG', slug: "federal-university-oye-ekiti" },
  { name: "Federal University Wukari", city: "Wukari", state: "Taraba", country_code: 'NG', slug: "federal-university-wukari" },
  { name: "Federal University Birnin Kebbi", city: "Birnin Kebbi", state: "Kebbi", country_code: 'NG', slug: "federal-university-birnin-kebbi" },
  { name: "Federal University Gusau", city: "Gusau", state: "Zamfara", country_code: 'NG', slug: "federal-university-gusau" },
  { name: "Michael Okpara University of Agriculture", city: "Umudike", state: "Abia", country_code: 'NG', slug: "michael-okpara-university-of-agriculture" },
  { name: "Modibbo Adama University", city: "Yola", state: "Adamawa", country_code: 'NG', slug: "modibbo-adama-university" },
  { name: "National Open University of Nigeria", city: "Abuja", state: "FCT", country_code: 'NG', slug: "national-open-university-of-nigeria" },
  { name: "Nigeria Police Academy", city: "Wudil", state: "Kano", country_code: 'NG', slug: "nigeria-police-academy" },
  { name: "Nigerian Defence Academy", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "nigerian-defence-academy" },
  { name: "Nnamdi Azikiwe University", city: "Awka", state: "Anambra", country_code: 'NG', slug: "nnamdi-azikiwe-university" },
  { name: "Obafemi Awolowo University", city: "Ile-Ife", state: "Osun", country_code: 'NG', slug: "obafemi-awolowo-university" },
  { name: "University of Abuja", city: "Gwagwalada", state: "FCT", country_code: 'NG', slug: "university-of-abuja" },
  { name: "Federal University of Agriculture, Abeokuta", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "federal-university-of-agriculture-abeokuta" },
  { name: "Joseph Sarwuan Tarka University", city: "Makurdi", state: "Benue", country_code: 'NG', slug: "joseph-sarwuan-tarka-university" },
  { name: "University of Benin", city: "Benin City", state: "Edo", country_code: 'NG', slug: "university-of-benin" },
  { name: "University of Calabar", city: "Calabar", state: "Cross River", country_code: 'NG', slug: "university-of-calabar" },
  { name: "University of Ibadan", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "university-of-ibadan" },
  { name: "University of Ilorin", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "university-of-ilorin" },
  { name: "University of Jos", city: "Jos", state: "Plateau", country_code: 'NG', slug: "university-of-jos" },
  { name: "University of Lagos", city: "Lagos", state: "Lagos", country_code: 'NG', slug: "university-of-lagos" },
  { name: "University of Maiduguri", city: "Maiduguri", state: "Borno", country_code: 'NG', slug: "university-of-maiduguri" },
  { name: "University of Nigeria, Nsukka", city: "Nsukka", state: "Enugu", country_code: 'NG', slug: "university-of-nigeria-nsukka" },
  { name: "University of Port Harcourt", city: "Port Harcourt", state: "Rivers", country_code: 'NG', slug: "university-of-port-harcourt" },
  { name: "University of Uyo", city: "Uyo", state: "Akwa Ibom", country_code: 'NG', slug: "university-of-uyo" },
  { name: "Usmanu Danfodiyo University", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "usmanu-danfodiyo-university" },
  { name: "Nigerian Maritime University", city: "Okerenkoko", state: "Delta", country_code: 'NG', slug: "nigerian-maritime-university" },
  { name: "Air Force Institute of Technology", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "air-force-institute-of-technology" },
  { name: "Nigerian Army University", city: "Biu", state: "Borno", country_code: 'NG', slug: "nigerian-army-university" },
  { name: "Federal University of Health Sciences, Otukpo", city: "Otukpo", state: "Benue", country_code: 'NG', slug: "federal-university-of-health-sciences-otukpo" },
  { name: "Federal University of Agriculture, Zuru", city: "Zuru", state: "Kebbi", country_code: 'NG', slug: "federal-university-of-agriculture-zuru" },
  { name: "Federal University of Technology, Babura", city: "Babura", state: "Jigawa", country_code: 'NG', slug: "federal-university-of-technology-babura" },
  { name: "Federal University of Technology, Ikot Abasi", city: "Ikot Abasi", state: "Akwa Ibom", country_code: 'NG', slug: "federal-university-of-technology-ikot-abasi" },
  { name: "Federal University of Health Sciences, Azare", city: "Azare", state: "Bauchi", country_code: 'NG', slug: "federal-university-of-health-sciences-azare" },
  { name: "Federal University of Health Sciences, Ila Orangun", city: "Ila Orangun", state: "Osun", country_code: 'NG', slug: "federal-university-of-health-sciences-ila-orangun" },
  { name: "David Umahi Federal University of Medical Sciences", city: "Uburu", state: "Ebonyi", country_code: 'NG', slug: "david-umahi-federal-university-of-medical-sciences" },
  { name: "Admiralty University", city: "Ibusa", state: "Delta", country_code: 'NG', slug: "admiralty-university" },
  { name: "Federal University of Transportation", city: "Daura", state: "Katsina", country_code: 'NG', slug: "federal-university-of-transportation" },
  { name: "African Aviation and Aerospace University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "african-aviation-and-aerospace-university" },
  { name: "National University of Science and Technology", city: "Abuja", state: "FCT", country_code: 'NG', slug: "national-university-of-science-and-technology" },
  { name: "Federal University of Agriculture, Bassambiri", city: "Bassambiri", state: "Bayelsa", country_code: 'NG', slug: "federal-university-of-agriculture-bassambiri" },
  { name: "Federal University of Health Sciences, Kwale", city: "Kwale", state: "Delta", country_code: 'NG', slug: "federal-university-of-health-sciences-kwale" },
  { name: "Federal University of Health Sciences, Katsina", city: "Katsina", state: "Katsina", country_code: 'NG', slug: "federal-university-of-health-sciences-katsina" },
  { name: "Federal University of Agriculture, Mubi", city: "Mubi", state: "Adamawa", country_code: 'NG', slug: "federal-university-of-agriculture-mubi" },
  { name: "Federal University of Education, Zaria", city: "Zaria", state: "Kaduna", country_code: 'NG', slug: "federal-university-of-education-zaria" },
  { name: "Alvan Ikoku Federal University of Education", city: "Owerri", state: "Imo", country_code: 'NG', slug: "alvan-ikoku-federal-university-of-education" },
  { name: "Yusuf Maitama Sule Federal University of Education", city: "Kano", state: "Kano", country_code: 'NG', slug: "yusuf-maitama-sule-federal-university-of-education" },
  { name: "Adeyemi Federal University of Education", city: "Ondo", state: "Ondo", country_code: 'NG', slug: "adeyemi-federal-university-of-education" },
  { name: "Federal University of Allied Health Sciences", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "federal-university-of-allied-health-sciences" },
  { name: "Federal University of Medicine and Medical Sciences", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "federal-university-of-medicine-and-medical-sciences" },
  { name: "Federal University of Education, Pankshin", city: "Pankshin", state: "Plateau", country_code: 'NG', slug: "federal-university-of-education-pankshin" },
  { name: "Federal University of Education, Kontagora", city: "Kontagora", state: "Niger", country_code: 'NG', slug: "federal-university-of-education-kontagora" },
  { name: "University of Maritime Studies", city: "Oron", state: "Akwa Ibom", country_code: 'NG', slug: "university-of-maritime-studies" },
  { name: "Federal University of Environment and Technology", city: "Tai", state: "Rivers", country_code: 'NG', slug: "federal-university-of-environment-and-technology" },
  { name: "Federal University of Applied Sciences", city: "Kachia", state: "Kaduna", country_code: 'NG', slug: "federal-university-of-applied-sciences" },
  { name: "Tai Solarin Federal University of Education", city: "Ijagun", state: "Ogun", country_code: 'NG', slug: "tai-solarin-federal-university-of-education" },
  { name: "Federal University of Agriculture and Developmental Studies", city: "Iragbiji", state: "Osun", country_code: 'NG', slug: "federal-university-of-agriculture-and-developmental-studies" },
  { name: "Federal University of Technology and Environmental Studies", city: "Iyin-Ekiti", state: "Ekiti", country_code: 'NG', slug: "federal-university-of-technology-and-environmental-studies" },
  { name: "Federal University of Agriculture and Technology, Okeho", city: "Okeho", state: "Oyo", country_code: 'NG', slug: "federal-university-of-agriculture-and-technology-okeho" },
  { name: "Federal University of Health Science and Technology", city: "Tsafe", state: "Zamfara", country_code: 'NG', slug: "federal-university-of-health-science-and-technology" },
  { name: "Federal University of Agriculture and Technology, Obio-Akpa", city: "Obio-Akpa", state: "Akwa Ibom", country_code: 'NG', slug: "federal-university-of-agriculture-and-technology-obio-akpa" },
  { name: "Federal University of Science and Technology, Epe", city: "Epe", state: "Lagos", country_code: 'NG', slug: "federal-university-of-science-and-technology-epe" },
  { name: "Federal University of Science and Technology, Kabo", city: "Kabo", state: "Kano", country_code: 'NG', slug: "federal-university-of-science-and-technology-kabo" },
  { name: "Rivers State University", city: "Port Harcourt", state: "Rivers", country_code: 'NG', slug: "rivers-state-university" },
  { name: "Ambrose Alli University", city: "Ekpoma", state: "Edo", country_code: 'NG', slug: "ambrose-alli-university" },
  { name: "Abia State University", city: "Uturu", state: "Abia", country_code: 'NG', slug: "abia-state-university" },
  { name: "Ekiti State University", city: "Ado-Ekiti", state: "Ekiti", country_code: 'NG', slug: "ekiti-state-university" },
  { name: "Enugu State University of Science and Technology", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "enugu-state-university-of-science-and-technology" },
  { name: "Olabisi Onabanjo University", city: "Ago-Iwoye", state: "Ogun", country_code: 'NG', slug: "olabisi-onabanjo-university" },
  { name: "Lagos State University", city: "Ojo", state: "Lagos", country_code: 'NG', slug: "lagos-state-university" },
  { name: "Ladoke Akintola University of Technology", city: "Ogbomoso", state: "Oyo", country_code: 'NG', slug: "ladoke-akintola-university-of-technology" },
  { name: "Benue State University", city: "Makurdi", state: "Benue", country_code: 'NG', slug: "benue-state-university" },
  { name: "Delta State University", city: "Abraka", state: "Delta", country_code: 'NG', slug: "delta-state-university" },
  { name: "Imo State University", city: "Owerri", state: "Imo", country_code: 'NG', slug: "imo-state-university" },
  { name: "Adekunle Ajasin University", city: "Akungba", state: "Ondo", country_code: 'NG', slug: "adekunle-ajasin-university" },
  { name: "Prince Abubakar Audu University", city: "Anyigba", state: "Kogi", country_code: 'NG', slug: "prince-abubakar-audu-university" },
  { name: "Chukwuemeka Odumegwu Ojukwu University", city: "Uli", state: "Anambra", country_code: 'NG', slug: "chukwuemeka-odumegwu-ojukwu-university" },
  { name: "Ebonyi State University", city: "Abakaliki", state: "Ebonyi", country_code: 'NG', slug: "ebonyi-state-university" },
  { name: "Aliko Dangote University of Science and Technology", city: "Wudil", state: "Kano", country_code: 'NG', slug: "aliko-dangote-university-of-science-and-technology" },
  { name: "Niger Delta University", city: "Yenagoa", state: "Bayelsa", country_code: 'NG', slug: "niger-delta-university" },
  { name: "Adamawa State University", city: "Mubi", state: "Adamawa", country_code: 'NG', slug: "adamawa-state-university" },
  { name: "Nasarawa State University", city: "Keffi", state: "Nasarawa", country_code: 'NG', slug: "nasarawa-state-university" },
  { name: "University of Cross River State", city: "Calabar", state: "Cross River", country_code: 'NG', slug: "university-of-cross-river-state" },
  { name: "Gombe State University", city: "Gombe", state: "Gombe", country_code: 'NG', slug: "gombe-state-university" },
  { name: "Kaduna State University", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "kaduna-state-university" },
  { name: "Ibrahim Badamasi Babangida University", city: "Lapai", state: "Niger", country_code: 'NG', slug: "ibrahim-badamasi-babangida-university" },
  { name: "Plateau State University", city: "Bokkos", state: "Plateau", country_code: 'NG', slug: "plateau-state-university" },
  { name: "Yobe State University", city: "Damaturu", state: "Yobe", country_code: 'NG', slug: "yobe-state-university" },
  { name: "Kebbi State University of Science and Technology", city: "Aliero", state: "Kebbi", country_code: 'NG', slug: "kebbi-state-university-of-science-and-technology" },
  { name: "Umaru Musa Yar'adua University", city: "Katsina", state: "Katsina", country_code: 'NG', slug: "umaru-musa-yar-adua-university" },
  { name: "Osun State University", city: "Osogbo", state: "Osun", country_code: 'NG', slug: "osun-state-university" },
  { name: "Olusegun Agagu University of Science and Technology", city: "Okitipupa", state: "Ondo", country_code: 'NG', slug: "olusegun-agagu-university-of-science-and-technology" },
  { name: "Taraba State University", city: "Jalingo", state: "Taraba", country_code: 'NG', slug: "taraba-state-university" },
  { name: "Kwara State University", city: "Malete", state: "Kwara", country_code: 'NG', slug: "kwara-state-university" },
  { name: "Sokoto State University", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "sokoto-state-university" },
  { name: "Akwa Ibom State University", city: "Ikot Akpaden", state: "Akwa Ibom", country_code: 'NG', slug: "akwa-ibom-state-university" },
  { name: "Ignatius Ajuru University of Education", city: "Port Harcourt", state: "Rivers", country_code: 'NG', slug: "ignatius-ajuru-university-of-education" },
  { name: "Bauchi State University", city: "Gadau", state: "Bauchi", country_code: 'NG', slug: "bauchi-state-university" },
  { name: "Northwest University", city: "Kano", state: "Kano", country_code: 'NG', slug: "northwest-university" },
  { name: "First Technical University", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "first-technical-university" },
  { name: "Sule Lamido University", city: "Kafin Hausa", state: "Jigawa", country_code: 'NG', slug: "sule-lamido-university" },
  { name: "University of Medical Sciences", city: "Ondo", state: "Ondo", country_code: 'NG', slug: "university-of-medical-sciences" },
  { name: "Edo State University", city: "Iyamho", state: "Edo", country_code: 'NG', slug: "edo-state-university" },
  { name: "Kingsley Ozumba Mbadiwe University", city: "Ogboko", state: "Imo", country_code: 'NG', slug: "kingsley-ozumba-mbadiwe-university" },
  { name: "University of Africa", city: "Toru-Orua", state: "Bayelsa", country_code: 'NG', slug: "university-of-africa" },
  { name: "Kashim Ibrahim University", city: "Maiduguri", state: "Borno", country_code: 'NG', slug: "kashim-ibrahim-university" },
  { name: "Moshood Abiola University of Science and Technology", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "moshood-abiola-university-of-science-and-technology" },
  { name: "Zamfara State University", city: "Talata Mafara", state: "Zamfara", country_code: 'NG', slug: "zamfara-state-university" },
  { name: "Bayelsa Medical University", city: "Yenagoa", state: "Bayelsa", country_code: 'NG', slug: "bayelsa-medical-university" },
  { name: "University of Agriculture and Environmental Sciences", city: "Umuagwo", state: "Imo", country_code: 'NG', slug: "university-of-agriculture-and-environmental-sciences" },
  { name: "Confluence University of Science and Technology", city: "Osara", state: "Kogi", country_code: 'NG', slug: "confluence-university-of-science-and-technology" },
  { name: "Bamidele Olumilua University of Education, Science and Technology", city: "Ikere", state: "Ekiti", country_code: 'NG', slug: "bamidele-olumilua-university-of-education-science-and-technology" },
  { name: "University of Delta", city: "Agbor", state: "Delta", country_code: 'NG', slug: "university-of-delta" },
  { name: "Delta University of Science and Technology", city: "Ozoro", state: "Delta", country_code: 'NG', slug: "delta-university-of-science-and-technology" },
  { name: "Dennis Osadebay University", city: "Asaba", state: "Delta", country_code: 'NG', slug: "dennis-osadebay-university" },
  { name: "Lagos State University of Education", city: "Ijanikin", state: "Lagos", country_code: 'NG', slug: "lagos-state-university-of-education" },
  { name: "Lagos State University of Science and Technology", city: "Ikorodu", state: "Lagos", country_code: 'NG', slug: "lagos-state-university-of-science-and-technology" },
  { name: "Shehu Shagari University of Education", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "shehu-shagari-university-of-education" },
  { name: "State University of Medical and Applied Sciences", city: "Igbo-Eno", state: "Enugu", country_code: 'NG', slug: "state-university-of-medical-and-applied-sciences" },
  { name: "University of Ilesa", city: "Ilesa", state: "Osun", country_code: 'NG', slug: "university-of-ilesa" },
  { name: "Emmanuel Alayande University of Education", city: "Oyo", state: "Oyo", country_code: 'NG', slug: "emmanuel-alayande-university-of-education" },
  { name: "Kogi State University", city: "Kabba", state: "Kogi", country_code: 'NG', slug: "kogi-state-university" },
  { name: "AbdulKadir Kure University", city: "Minna", state: "Niger", country_code: 'NG', slug: "abdulkadir-kure-university" },
  { name: "Kwara State University of Education", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "kwara-state-university-of-education" },
  { name: "Abdulsalam Abubakar University of Agriculture and Climate Action", city: "Mokwa", state: "Niger", country_code: 'NG', slug: "abdulsalam-abubakar-university-of-agriculture-and-climate-action" },
  { name: "Ebonyi State University of ICT, Science and Technology", city: "Oferekpe", state: "Ebonyi", country_code: 'NG', slug: "ebonyi-state-university-of-ict-science-and-technology" },
  { name: "Cross River University of Education and Entrepreneurship", city: "Akamkpa", state: "Cross River", country_code: 'NG', slug: "cross-river-university-of-education-and-entrepreneurship" },
  { name: "Benue State University of Agriculture, Science and Technology", city: "Ihugh", state: "Benue", country_code: 'NG', slug: "benue-state-university-of-agriculture-science-and-technology" },
  { name: "University of Aeronautics and Aerospace Engineering", city: "Ezza", state: "Ebonyi", country_code: 'NG', slug: "university-of-aeronautics-and-aerospace-engineering" },
  { name: "University of Innovation, Science and Technology", city: "Omuma", state: "Imo", country_code: 'NG', slug: "university-of-innovation-science-and-technology" },
  { name: "Babcock University", city: "Ilishan-Remo", state: "Ogun", country_code: 'NG', slug: "babcock-university" },
  { name: "Igbinedion University", city: "Okada", state: "Edo", country_code: 'NG', slug: "igbinedion-university" },
  { name: "Madonna University", city: "Okija", state: "Anambra", country_code: 'NG', slug: "madonna-university" },
  { name: "Bowen University", city: "Iwo", state: "Osun", country_code: 'NG', slug: "bowen-university" },
  { name: "Benson Idahosa University", city: "Benin City", state: "Edo", country_code: 'NG', slug: "benson-idahosa-university" },
  { name: "Covenant University", city: "Ota", state: "Ogun", country_code: 'NG', slug: "covenant-university" },
  { name: "Pan-Atlantic University", city: "Lekki", state: "Lagos", country_code: 'NG', slug: "pan-atlantic-university" },
  { name: "American University of Nigeria", city: "Yola", state: "Adamawa", country_code: 'NG', slug: "american-university-of-nigeria" },
  { name: "Ajayi Crowther University", city: "Oyo", state: "Oyo", country_code: 'NG', slug: "ajayi-crowther-university" },
  { name: "Al-Hikmah University", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "al-hikmah-university" },
  { name: "Al-Qalam University", city: "Katsina", state: "Katsina", country_code: 'NG', slug: "al-qalam-university" },
  { name: "Bells University of Technology", city: "Ota", state: "Ogun", country_code: 'NG', slug: "bells-university-of-technology" },
  { name: "Bingham University", city: "Karu", state: "Nasarawa", country_code: 'NG', slug: "bingham-university" },
  { name: "Caritas University", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "caritas-university" },
  { name: "Crawford University", city: "Igbesa", state: "Ogun", country_code: 'NG', slug: "crawford-university" },
  { name: "Crescent University", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "crescent-university" },
  { name: "Kwararafa University", city: "Wukari", state: "Taraba", country_code: 'NG', slug: "kwararafa-university" },
  { name: "Lead City University", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "lead-city-university" },
  { name: "Novena University", city: "Ogume", state: "Delta", country_code: 'NG', slug: "novena-university" },
  { name: "Redeemer's University", city: "Ede", state: "Osun", country_code: 'NG', slug: "redeemer-s-university" },
  { name: "Renaissance University", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "renaissance-university" },
  { name: "University of Mkar", city: "Mkar", state: "Benue", country_code: 'NG', slug: "university-of-mkar" },
  { name: "Joseph Ayo Babalola University", city: "Ikeji-Arakeji", state: "Osun", country_code: 'NG', slug: "joseph-ayo-babalola-university" },
  { name: "Achievers University", city: "Owo", state: "Ondo", country_code: 'NG', slug: "achievers-university" },
  { name: "Caleb University", city: "Imota", state: "Lagos", country_code: 'NG', slug: "caleb-university" },
  { name: "Fountain University", city: "Osogbo", state: "Osun", country_code: 'NG', slug: "fountain-university" },
  { name: "African University of Science and Technology", city: "Abuja", state: "FCT", country_code: 'NG', slug: "african-university-of-science-and-technology" },
  { name: "Obong University", city: "Obong Ntak", state: "Akwa Ibom", country_code: 'NG', slug: "obong-university" },
  { name: "Salem University", city: "Lokoja", state: "Kogi", country_code: 'NG', slug: "salem-university" },
  { name: "Tansian University", city: "Umunya", state: "Anambra", country_code: 'NG', slug: "tansian-university" },
  { name: "Veritas University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "veritas-university" },
  { name: "Wesley University", city: "Ondo", state: "Ondo", country_code: 'NG', slug: "wesley-university" },
  { name: "Western Delta University", city: "Oghara", state: "Delta", country_code: 'NG', slug: "western-delta-university" },
  { name: "Afe Babalola University", city: "Ado-Ekiti", state: "Ekiti", country_code: 'NG', slug: "afe-babalola-university" },
  { name: "Godfrey Okoye University", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "godfrey-okoye-university" },
  { name: "Nile University of Nigeria", city: "Abuja", state: "FCT", country_code: 'NG', slug: "nile-university-of-nigeria" },
  { name: "Oduduwa University", city: "Ipetumodu", state: "Osun", country_code: 'NG', slug: "oduduwa-university" },
  { name: "Paul University", city: "Awka", state: "Anambra", country_code: 'NG', slug: "paul-university" },
  { name: "Rhema University", city: "Obeama-Asa", state: "Rivers", country_code: 'NG', slug: "rhema-university" },
  { name: "Wellspring University", city: "Evbuobanosa", state: "Edo", country_code: 'NG', slug: "wellspring-university" },
  { name: "Adeleke University", city: "Ede", state: "Osun", country_code: 'NG', slug: "adeleke-university" },
  { name: "Baze University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "baze-university" },
  { name: "Landmark University", city: "Omu-Aran", state: "Kwara", country_code: 'NG', slug: "landmark-university" },
  { name: "Glorious Vision University", city: "Ogwa", state: "Edo", country_code: 'NG', slug: "glorious-vision-university" },
  { name: "Elizade University", city: "Ilara-Mokin", state: "Ondo", country_code: 'NG', slug: "elizade-university" },
  { name: "Evangel University", city: "Akaeze", state: "Ebonyi", country_code: 'NG', slug: "evangel-university" },
  { name: "Gregory University", city: "Uturu", state: "Abia", country_code: 'NG', slug: "gregory-university" },
  { name: "McPherson University", city: "Seriki Sotayo", state: "Ogun", country_code: 'NG', slug: "mcpherson-university" },
  { name: "Southwestern University", city: "Okun Owa", state: "Ogun", country_code: 'NG', slug: "southwestern-university" },
  { name: "Augustine University", city: "Ilara", state: "Lagos", country_code: 'NG', slug: "augustine-university" },
  { name: "Chrisland University", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "chrisland-university" },
  { name: "Edwin Clark University", city: "Kaigbodo", state: "Delta", country_code: 'NG', slug: "edwin-clark-university" },
  { name: "Hallmark University", city: "Ijebu-Itele", state: "Ogun", country_code: 'NG', slug: "hallmark-university" },
  { name: "Hezekiah University", city: "Umudi", state: "Imo", country_code: 'NG', slug: "hezekiah-university" },
  { name: "Kings University", city: "Ode-Omu", state: "Osun", country_code: 'NG', slug: "kings-university" },
  { name: "Michael and Cecilia Ibru University", city: "Agbarha-Otor", state: "Delta", country_code: 'NG', slug: "michael-and-cecilia-ibru-university" },
  { name: "Mountain Top University", city: "Makogi-Oba", state: "Ogun", country_code: 'NG', slug: "mountain-top-university" },
  { name: "Ritman University", city: "Ikot Ekpene", state: "Akwa Ibom", country_code: 'NG', slug: "ritman-university" },
  { name: "Summit University", city: "Offa", state: "Kwara", country_code: 'NG', slug: "summit-university" },
  { name: "Christopher University", city: "Mowe", state: "Ogun", country_code: 'NG', slug: "christopher-university" },
  { name: "Kola Daisi University", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "kola-daisi-university" },
  { name: "Anchor University", city: "Ayobo", state: "Lagos", country_code: 'NG', slug: "anchor-university" },
  { name: "Dominican University", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "dominican-university" },
  { name: "Legacy University", city: "Okija", state: "Anambra", country_code: 'NG', slug: "legacy-university" },
  { name: "Arthur Jarvis University", city: "Akpabuyo", state: "Cross River", country_code: 'NG', slug: "arthur-jarvis-university" },
  { name: "Ojaja University", city: "Eiyenkorin", state: "Kwara", country_code: 'NG', slug: "ojaja-university" },
  { name: "Coal City University", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "coal-city-university" },
  { name: "Clifford University", city: "Owerrinta", state: "Abia", country_code: 'NG', slug: "clifford-university" },
  { name: "Spiritan University", city: "Nneochi", state: "Abia", country_code: 'NG', slug: "spiritan-university" },
  { name: "Precious Cornerstone University", city: "Oyo", state: "Oyo", country_code: 'NG', slug: "precious-cornerstone-university" },
  { name: "PAMO University of Medical Sciences", city: "Port Harcourt", state: "Rivers", country_code: 'NG', slug: "pamo-university-of-medical-sciences" },
  { name: "Atiba University", city: "Oyo", state: "Oyo", country_code: 'NG', slug: "atiba-university" },
  { name: "Eko University of Medical and Health Sciences", city: "Ijanikin", state: "Lagos", country_code: 'NG', slug: "eko-university-of-medical-and-health-sciences" },
  { name: "Skyline University", city: "Kano", state: "Kano", country_code: 'NG', slug: "skyline-university" },
  { name: "Greenfield University", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "greenfield-university" },
  { name: "Dominion University", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "dominion-university" },
  { name: "Trinity University", city: "Yaba", state: "Lagos", country_code: 'NG', slug: "trinity-university" },
  { name: "Westland University", city: "Iwo", state: "Osun", country_code: 'NG', slug: "westland-university" },
  { name: "Topfaith University", city: "Mkpatak", state: "Akwa Ibom", country_code: 'NG', slug: "topfaith-university" },
  { name: "Thomas Adewumi University", city: "Oko-Irese", state: "Kwara", country_code: 'NG', slug: "thomas-adewumi-university" },
  { name: "Maranatha University", city: "Lagos", state: "Lagos", country_code: 'NG', slug: "maranatha-university" },
  { name: "Ave Maria University", city: "Piyanko", state: "Nasarawa", country_code: 'NG', slug: "ave-maria-university" },
  { name: "Al-Istiqama University", city: "Sumaila", state: "Kano", country_code: 'NG', slug: "al-istiqama-university" },
  { name: "Mudiame University", city: "Irrua", state: "Edo", country_code: 'NG', slug: "mudiame-university" },
  { name: "Havilla University", city: "Nde-Ikom", state: "Cross River", country_code: 'NG', slug: "havilla-university" },
  { name: "Claretian University of Nigeria", city: "Nekede", state: "Imo", country_code: 'NG', slug: "claretian-university-of-nigeria" },
  { name: "Karl-Kumm University", city: "Vom", state: "Plateau", country_code: 'NG', slug: "karl-kumm-university" },
  { name: "James Hope University", city: "Lekki", state: "Lagos", country_code: 'NG', slug: "james-hope-university" },
  { name: "Maryam Abacha American University of Nigeria", city: "Kano", state: "Kano", country_code: 'NG', slug: "maryam-abacha-american-university-of-nigeria" },
  { name: "Capital City University", city: "Kano", state: "Kano", country_code: 'NG', slug: "capital-city-university" },
  { name: "Ahman Pategi University", city: "Patigi", state: "Kwara", country_code: 'NG', slug: "ahman-pategi-university" },
  { name: "University of Offa", city: "Offa", state: "Kwara", country_code: 'NG', slug: "university-of-offa" },
  { name: "Mewar International University", city: "Masaka", state: "Nasarawa", country_code: 'NG', slug: "mewar-international-university" },
  { name: "Edusoko University", city: "Bida", state: "Niger", country_code: 'NG', slug: "edusoko-university" },
  { name: "Philomath University", city: "Kuje", state: "FCT", country_code: 'NG', slug: "philomath-university" },
  { name: "Khadija University", city: "Majia", state: "Jigawa", country_code: 'NG', slug: "khadija-university" },
  { name: "ANAN University", city: "Kwall", state: "Plateau", country_code: 'NG', slug: "anan-university" },
  { name: "North Eastern University", city: "Gombe", state: "Gombe", country_code: 'NG', slug: "north-eastern-university" },
  { name: "Al-Ansar University", city: "Maiduguri", state: "Borno", country_code: 'NG', slug: "al-ansar-university" },
  { name: "Margaret Lawrence University", city: "Umunede", state: "Delta", country_code: 'NG', slug: "margaret-lawrence-university" },
  { name: "Khalifa Isiyaku Rabiu University", city: "Kano", state: "Kano", country_code: 'NG', slug: "khalifa-isiyaku-rabiu-university" },
  { name: "Sports University", city: "Idumuje-Ugboko", state: "Delta", country_code: 'NG', slug: "sports-university" },
  { name: "Baba Ahmed University", city: "Kano", state: "Kano", country_code: 'NG', slug: "baba-ahmed-university" },
  { name: "Saisa University of Medical Sciences and Technology", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "saisa-university-of-medical-sciences-and-technology" },
  { name: "Nigerian British University", city: "Asa", state: "Abia", country_code: 'NG', slug: "nigerian-british-university" },
  { name: "Peter University", city: "Achina-Onneh", state: "Anambra", country_code: 'NG', slug: "peter-university" },
  { name: "Newgate University", city: "Minna", state: "Niger", country_code: 'NG', slug: "newgate-university" },
  { name: "European University of Nigeria", city: "Duboyi", state: "FCT", country_code: 'NG', slug: "european-university-of-nigeria" },
  { name: "Northwest University Sokoto", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "northwest-university-sokoto" },
  { name: "Rayhaan University", city: "Birnin Kebbi", state: "Kebbi", country_code: 'NG', slug: "rayhaan-university" },
  { name: "Muhammad Kamalud-Deen University", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "muhammad-kamalud-deen-university" },
  { name: "Sam Maris University", city: "Supare", state: "Ondo", country_code: 'NG', slug: "sam-maris-university" },
  { name: "Aletheia University", city: "Ago-Iwoye", state: "Ogun", country_code: 'NG', slug: "aletheia-university" },
  { name: "Lux Mundi University", city: "Umuahia", state: "Abia", country_code: 'NG', slug: "lux-mundi-university" },
  { name: "Maduka University", city: "Ekwegbe", state: "Enugu", country_code: 'NG', slug: "maduka-university" },
  { name: "Peaceland University", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "peaceland-university" },
  { name: "Amadeus University", city: "Amizi", state: "Abia", country_code: 'NG', slug: "amadeus-university" },
  { name: "Vision University", city: "Ikogbo", state: "Ogun", country_code: 'NG', slug: "vision-university" },
  { name: "Azman University", city: "Kano", state: "Kano", country_code: 'NG', slug: "azman-university" },
  { name: "Huda University", city: "Gusau", state: "Zamfara", country_code: 'NG', slug: "huda-university" },
  { name: "Franco British International University", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "franco-british-international-university" },
  { name: "Canadian University of Nigeria", city: "Abuja", state: "FCT", country_code: 'NG', slug: "canadian-university-of-nigeria" },
  { name: "Gerar University of Medical Science", city: "Imope-Ijebu", state: "Ogun", country_code: 'NG', slug: "gerar-university-of-medical-science" },
  { name: "British Canadian University", city: "Obudu", state: "Cross River", country_code: 'NG', slug: "british-canadian-university" },
  { name: "Hensard University", city: "Toru-Orua", state: "Bayelsa", country_code: 'NG', slug: "hensard-university" },
  { name: "Amaj University", city: "Kwali", state: "FCT", country_code: 'NG', slug: "amaj-university" },
  { name: "Phoenix University", city: "Agwada", state: "Nasarawa", country_code: 'NG', slug: "phoenix-university" },
  { name: "Wigwe University", city: "Isiokpo", state: "Rivers", country_code: 'NG', slug: "wigwe-university" },
  { name: "Hillside University of Science and Technology", city: "Okemesi", state: "Ekiti", country_code: 'NG', slug: "hillside-university-of-science-and-technology" },
  { name: "University on the Niger", city: "Umunya", state: "Anambra", country_code: 'NG', slug: "university-on-the-niger" },
  { name: "Elrazi Medical University", city: "Yargaya", state: "Kano", country_code: 'NG', slug: "elrazi-medical-university" },
  { name: "Venite University", city: "Iloro-Ekiti", state: "Ekiti", country_code: 'NG', slug: "venite-university" },
  { name: "Shanahan University", city: "Onitsha", state: "Anambra", country_code: 'NG', slug: "shanahan-university" },
  { name: "The Duke Medical University", city: "Calabar", state: "Cross River", country_code: 'NG', slug: "the-duke-medical-university" },
  { name: "Mercy Medical University", city: "Iwo", state: "Osun", country_code: 'NG', slug: "mercy-medical-university" },
  { name: "Cosmopolitan University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "cosmopolitan-university" },
  { name: "Miva Open University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "miva-open-university" },
  { name: "Iconic Open University", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "iconic-open-university" },
  { name: "West Midlands Open University", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "west-midlands-open-university" },
  { name: "Al-Muhibbah Open University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "al-muhibbah-open-university" },
  { name: "El-Amin University", city: "Minna", state: "Niger", country_code: 'NG', slug: "el-amin-university" },
  { name: "College of Petroleum and Energy Studies", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "college-of-petroleum-and-energy-studies" },
  { name: "Jewel University", city: "Gombe", state: "Gombe", country_code: 'NG', slug: "jewel-university" },
  { name: "Prime University", city: "Kuje", state: "FCT", country_code: 'NG', slug: "prime-university" },
  { name: "Nigerian University of Technology and Management", city: "Apapa", state: "Lagos", country_code: 'NG', slug: "nigerian-university-of-technology-and-management" },
  { name: "Al-Bayan University", city: "Ankpa", state: "Kogi", country_code: 'NG', slug: "al-bayan-university" },
  { name: "Lighthouse University", city: "Evbobanosa", state: "Edo", country_code: 'NG', slug: "lighthouse-university" },
  { name: "African University of Economics", city: "Abuja", state: "FCT", country_code: 'NG', slug: "african-university-of-economics" },
  { name: "New City University", city: "Ayetoro", state: "Ogun", country_code: 'NG', slug: "new-city-university" },
  { name: "University of Fortune", city: "Igbotako", state: "Ondo", country_code: 'NG', slug: "university-of-fortune" },
  { name: "Eranova University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "eranova-university" },
  { name: "Minaret University", city: "Ikirun", state: "Osun", country_code: 'NG', slug: "minaret-university" },
  { name: "Abdulrasaq Abubakar Toyin University", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "abdulrasaq-abubakar-toyin-university" },
  { name: "Southern Atlantic University", city: "Uyo", state: "Akwa Ibom", country_code: 'NG', slug: "southern-atlantic-university" },
  { name: "Lens University", city: "Ilemona", state: "Kwara", country_code: 'NG', slug: "lens-university" },
  { name: "Monarch University", city: "Iyesi-Ota", state: "Ogun", country_code: 'NG', slug: "monarch-university" },
  { name: "Tonine Iredia University of Communication", city: "Benin City", state: "Edo", country_code: 'NG', slug: "tonine-iredia-university-of-communication" },
  { name: "Isaac Balami University of Aeronautics and Management", city: "Lagos", state: "Lagos", country_code: 'NG', slug: "isaac-balami-university-of-aeronautics-and-management" },
  { name: "Kevin Eze University", city: "Mgbowo", state: "Enugu", country_code: 'NG', slug: "kevin-eze-university" },
  { name: "Tazkiyah University", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "tazkiyah-university" },
  { name: "Leadership University", city: "Abuja", state: "FCT", country_code: 'NG', slug: "leadership-university" },
  { name: "Jimoh Babalola University", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "jimoh-babalola-university" },
  { name: "Bridget University", city: "Mbaise", state: "Imo", country_code: 'NG', slug: "bridget-university" },
  { name: "Greenland University", city: "Jalingo", state: "Taraba", country_code: 'NG', slug: "greenland-university" },
  { name: "JEFAP University", city: "Suleja", state: "Niger", country_code: 'NG', slug: "jefap-university" },
  { name: "Azione Verde University", city: "Amaigbo", state: "Imo", country_code: 'NG', slug: "azione-verde-university" },
  { name: "Unique Open University", city: "Ojo", state: "Lagos", country_code: 'NG', slug: "unique-open-university" },
  { name: "American Open University", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "american-open-university" },
  { name: "Yaba College of Technology", city: "Yaba", state: "Lagos", country_code: 'NG', slug: "yaba-college-of-technology" },
  { name: "Federal Polytechnic, Ilaro", city: "Ilaro", state: "Ogun", country_code: 'NG', slug: "federal-polytechnic-ilaro" },
  { name: "Federal Polytechnic, Nekede", city: "Nekede", state: "Imo", country_code: 'NG', slug: "federal-polytechnic-nekede" },
  { name: "Federal Polytechnic, Ado-Ekiti", city: "Ado-Ekiti", state: "Ekiti", country_code: 'NG', slug: "federal-polytechnic-ado-ekiti" },
  { name: "Auchi Polytechnic", city: "Auchi", state: "Edo", country_code: 'NG', slug: "auchi-polytechnic" },
  { name: "Lagos State Polytechnic", city: "Ikorodu", state: "Lagos", country_code: 'NG', slug: "lagos-state-polytechnic" },
  { name: "Moshood Abiola Polytechnic", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "moshood-abiola-polytechnic" },
  { name: "The Polytechnic, Ibadan", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "the-polytechnic-ibadan" },
  { name: "Kwara State Polytechnic", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "kwara-state-polytechnic" },
  { name: "Ken Saro-Wiwa Polytechnic", city: "Bori", state: "Rivers", country_code: 'NG', slug: "ken-saro-wiwa-polytechnic" },
  { name: "Lagos University Teaching Hospital", city: "Idi-Araba", state: "Lagos", country_code: 'NG', slug: "lagos-university-teaching-hospital" },
  { name: "Other — Lagos", city: "Lagos", state: "Lagos", country_code: 'NG', slug: "other-lagos" },
  { name: "Other — Abuja", city: "Abuja", state: "FCT", country_code: 'NG', slug: "other-abuja" },
  { name: "Other — Ibadan", city: "Ibadan", state: "Oyo", country_code: 'NG', slug: "other-ibadan" },
  { name: "Other — Kano", city: "Kano", state: "Kano", country_code: 'NG', slug: "other-kano" },
  { name: "Other — Port Harcourt", city: "Port Harcourt", state: "Rivers", country_code: 'NG', slug: "other-port-harcourt" },
  { name: "Other — Benin City", city: "Benin City", state: "Edo", country_code: 'NG', slug: "other-benin-city" },
  { name: "Other — Kaduna", city: "Kaduna", state: "Kaduna", country_code: 'NG', slug: "other-kaduna" },
  { name: "Other — Enugu", city: "Enugu", state: "Enugu", country_code: 'NG', slug: "other-enugu" },
  { name: "Other — Abeokuta", city: "Abeokuta", state: "Ogun", country_code: 'NG', slug: "other-abeokuta" },
  { name: "Other — Ilorin", city: "Ilorin", state: "Kwara", country_code: 'NG', slug: "other-ilorin" },
  { name: "Other — Jos", city: "Jos", state: "Plateau", country_code: 'NG', slug: "other-jos" },
  { name: "Other — Calabar", city: "Calabar", state: "Cross River", country_code: 'NG', slug: "other-calabar" },
  { name: "Other — Uyo", city: "Uyo", state: "Akwa Ibom", country_code: 'NG', slug: "other-uyo" },
  { name: "Other — Owerri", city: "Owerri", state: "Imo", country_code: 'NG', slug: "other-owerri" },
  { name: "Other — Warri", city: "Warri", state: "Delta", country_code: 'NG', slug: "other-warri" },
  { name: "Other — Onitsha", city: "Onitsha", state: "Anambra", country_code: 'NG', slug: "other-onitsha" },
  { name: "Other — Aba", city: "Aba", state: "Abia", country_code: 'NG', slug: "other-aba" },
  { name: "Other — Maiduguri", city: "Maiduguri", state: "Borno", country_code: 'NG', slug: "other-maiduguri" },
  { name: "Other — Sokoto", city: "Sokoto", state: "Sokoto", country_code: 'NG', slug: "other-sokoto" },
  { name: "Other — Akure", city: "Akure", state: "Ondo", country_code: 'NG', slug: "other-akure" },
  { name: "Other — Osogbo", city: "Osogbo", state: "Osun", country_code: 'NG', slug: "other-osogbo" },
  { name: "Other — Awka", city: "Awka", state: "Anambra", country_code: 'NG', slug: "other-awka" },
  { name: "Other — Asaba", city: "Asaba", state: "Delta", country_code: 'NG', slug: "other-asaba" },
  { name: "Other — Makurdi", city: "Makurdi", state: "Benue", country_code: 'NG', slug: "other-makurdi" },
  { name: "Other — Minna", city: "Minna", state: "Niger", country_code: 'NG', slug: "other-minna" },
  { name: "Other — Gombe", city: "Gombe", state: "Gombe", country_code: 'NG', slug: "other-gombe" },
  { name: "Other — Bauchi", city: "Bauchi", state: "Bauchi", country_code: 'NG', slug: "other-bauchi" },
  { name: "Other — Yenagoa", city: "Yenagoa", state: "Bayelsa", country_code: 'NG', slug: "other-yenagoa" },
  { name: "Other — Lokoja", city: "Lokoja", state: "Kogi", country_code: 'NG', slug: "other-lokoja" },
  { name: "Other — Jalingo", city: "Jalingo", state: "Taraba", country_code: 'NG', slug: "other-jalingo" },
  { name: "Other — Abakaliki", city: "Abakaliki", state: "Ebonyi", country_code: 'NG', slug: "other-abakaliki" },
  { name: "Other — Umuahia", city: "Umuahia", state: "Abia", country_code: 'NG', slug: "other-umuahia" },
  { name: "Other — Katsina", city: "Katsina", state: "Katsina", country_code: 'NG', slug: "other-katsina" },
  { name: "Other — Dutse", city: "Dutse", state: "Jigawa", country_code: 'NG', slug: "other-dutse" },
  { name: "Other — Damaturu", city: "Damaturu", state: "Yobe", country_code: 'NG', slug: "other-damaturu" },
  { name: "Other — Birnin Kebbi", city: "Birnin Kebbi", state: "Kebbi", country_code: 'NG', slug: "other-birnin-kebbi" },
  { name: "Other — Gusau", city: "Gusau", state: "Zamfara", country_code: 'NG', slug: "other-gusau" },
  { name: "Other — Lafia", city: "Lafia", state: "Nasarawa", country_code: 'NG', slug: "other-lafia" },
  { name: "Other — Yola", city: "Yola", state: "Adamawa", country_code: 'NG', slug: "other-yola" },
  { name: "Other (city in Nigeria)", city: "Nigeria", state: "Nigeria", country_code: 'NG', slug: "other-city-nigeria" },
];

export function formatCampusLabel(campus: Pick<MarketplaceCampus, 'name' | 'city'>): string {
  return campus.city ? `${campus.name} (${campus.city})` : campus.name;
}

export function isOtherCityCampus(campus: Pick<MarketplaceCampus, 'slug' | 'name'> | null | undefined): boolean {
  if (!campus) return false;
  return campus.slug === OTHER_CITY_CAMPUS_SLUG || campus.name === 'Other (city in Nigeria)';
}

export function filterCampusesByQuery<T extends { name: string; city: string; state?: string }>(
  campuses: T[],
  query: string
): T[] {
  const q = query.trim().toLowerCase();
  if (!q) return campuses;
  return campuses.filter((campus) => {
    const hay = `${campus.name} ${campus.city} ${campus.state || ''}`.toLowerCase();
    return hay.includes(q);
  });
}
