/**
 * Type-scale allowlist — the debt ledger for Wave T.
 *
 * The scale is six steps (`text-display` … `text-label`, tailwind.config.js).
 * Anything else that sets a text size — an arbitrary `text-[13px]`, a bare
 * `text-sm`, an inline `fontSize:` — is a violation, because those are exactly
 * the three vocabularies that produced twelve web sizes for seven roles and
 * five hardcoded px sizes that ignored the app's own text-size setting.
 *
 * Migrating the whole app in one commit is not reviewable, so this file records
 * what was already there. `apps/web/src/typeScaleLint.test.ts` fails when a
 * file exceeds its recorded count, or when an unlisted file gains one. The
 * numbers only ever go down: migrate a screen, then lower or delete its entry.
 *
 * Files with a count of 0 are not listed. `components/ui/**` is exempt — it is
 * where the primitives live.
 *
 * A handful of entries are permanent rather than debt (emoji sized with a text
 * utility, for instance); those carry a comment saying so.
 */

/**
 * Known violation counts, keyed by repo-root-relative path.
 * Snapshot of the tree at the time Wave T landed. Edit downward only: migrate a
 * screen to the six steps, then lower or delete its entry.
 *
 * 210 files, 3117 violations at the Wave T baseline.
 * 209 files, 2988 after the Wave T-2 pass (the text-[10px]/text-[9px] purge,
 * the text-md fix and the Button/Avatar/Tabs primitives).
 */
export const TYPE_SCALE_ALLOWLIST: Readonly<Record<string, number>> = {
  'components/AICompanionPanel.tsx': 27,
  'components/AIDisclaimer.tsx': 1,
  'components/AIGenerateQuestionsModal.tsx': 14,
  'components/AIToolsHub.tsx': 16,
  'components/AIUsageBadge.tsx': 3,
  'components/AIUsageInline.tsx': 1,
  'components/AccountDeletionModal.tsx': 11,
  'components/AccountImportModal.tsx': 4,
  'components/AccountPausedBanner.tsx': 1,
  'components/AccountSuspendedNotice.tsx': 6,
  'components/AddMembersModal.tsx': 11,
  'components/AddTransactionModal.tsx': 16,
  'components/AuthScreen.tsx': 24,
  'components/BlockedUsersModal.tsx': 8,
  'components/BudgetTrackerScreen.tsx': 69,
  'components/CampusScreen.tsx': 14,
  'components/ChallengesInboxModal.tsx': 15,
  // The ChatWindow decomposition (lane M8) split this file's 80 into five:
  // 65 here and 15 across components/chat/* below. Nothing was added — the
  // ledger's total is unchanged, and every one of these moved verbatim.
  'components/ChatWindow.tsx': 65,
  'components/CollaboratorsModal.tsx': 11,
  'components/ContactForm.tsx': 12,
  'components/CookieNoticeBanner.tsx': 18,
  'components/CramSessionScreen.tsx': 20,
  'components/CreateDeckModal.tsx': 7,
  'components/CreateFlashcardModal.tsx': 45,
  'components/CreateGroupModal.tsx': 9,
  'components/CreateGroupScreen.tsx': 18,
  'components/CreateJobScreen.tsx': 40,
  'components/CreateLabModal.tsx': 7,
  'components/CreateMarketplaceListingModal.tsx': 39,
  'components/CreatorProfileScreen.tsx': 15,
  'components/DailyGoalsProgress.tsx': 4,
  'components/DailyQuestsWidget.tsx': 9,
  'components/DailyQuizWidget.tsx': 12,
  // Two emoji glyphs (streak flame, achievement icon) sized with
  // text-2xl/text-3xl. Artwork, not a type role — the scale has no step
  // for a 30 px pictograph. Permanent; do not migrate.
  'components/DashboardScreen.tsx': 1,
  'components/DeckDetailScreen.tsx': 36,
  'components/DuplicateQuestionModal.tsx': 8,
  'components/EditMarketplaceListingModal.tsx': 17,
  'components/EditShopModal.tsx': 11,
  'components/ErrorBoundary.tsx': 3,
  'components/ExpenseSplitModal.tsx': 27,
  'components/FlashcardReviewScreen.tsx': 40,
  'components/FlashcardsScreen.tsx': 6,
  'components/GameResultScreen.tsx': 15,
  'components/GameScreen.tsx': 22,
  'components/GroupInfoModal.tsx': 26,
  'components/GroupInviteLinkPanel.tsx': 5,
  'components/GroupListItem.tsx': 3,
  'components/GroupPerformanceChart.tsx': 1,
  'components/ImportAndStudyModal.tsx': 1,
  'components/InvestModal.tsx': 33,
  'components/InviteFriendsScreen.tsx': 17,
  'components/InviteJoinScreen.tsx': 8,
  'components/JobCompanyScreen.tsx': 17,
  'components/JobDetailScreen.tsx': 47,
  'components/JobEmployerPipelineScreen.tsx': 15,
  'components/JobEmployerScreen.tsx': 15,
  'components/JobsBoardScreen.tsx': 47,
  'components/LearnStudyScreen.tsx': 7,
  'components/LegalPage.tsx': 6,
  'components/LibraryScreen.tsx': 4,
  'components/MakeOfferModal.tsx': 12,
  'components/MarketplaceCartScreen.tsx': 11,
  'components/MarketplaceFavoritesScreen.tsx': 9,
  'components/MarketplaceInquiriesScreen.tsx': 49,
  'components/MarketplaceListingDetailScreen.tsx': 144,
  'components/MarketplaceOrderDetailScreen.tsx': 23,
  'components/MarketplaceOrdersScreen.tsx': 5,
  'components/MarketplacePurchasesScreen.tsx': 13,
  'components/MarketplaceScreen.tsx': 39,
  'components/MasteryPanel.tsx': 6,
  'components/MatchStudyScreen.tsx': 5,
  'components/MessageInputBar.tsx': 8,
  'components/MessageItem.tsx': 29,
  'components/MyJobApplicationsScreen.tsx': 37,
  'components/MyJobPostingsScreen.tsx': 27,
  'components/MyListingsScreen.tsx': 27,
  'components/NewDirectMessageModal.tsx': 5,
  'components/NoteCollaboratorsModal.tsx': 17,
  'components/NoteEditorScreen.tsx': 27,
  'components/NoteImageGallery.tsx': 7,
  'components/NoteLearnPanel.tsx': 2,
  'components/NotePdfViewer.tsx': 4,
  'components/NoteShareAcceptScreen.tsx': 7,
  'components/NotificationModal.tsx': 3,
  'components/OfflineModeScreen.tsx': 16,
  'components/OnboardingFlow.tsx': 12,
  'components/QuestionModal.tsx': 29,
  'components/RecurringModal.tsx': 14,
  'components/RequestError.tsx': 6,
  'components/ResetPasswordScreen.tsx': 5,
  'components/SavedSessionsList.tsx': 3,
  'components/SellerCustomersScreen.tsx': 7,
  'components/SellerProfileScreen.tsx': 30,
  'components/SemesterProductsScreen.tsx': 10,
  'components/SetBudgetModal.tsx': 13,
  'components/SetMonthlyPlanModal.tsx': 16,
  'components/SettingsModal.tsx': 77,
  'components/SimulationControls.tsx': 19,
  'components/StudyProductDraftsScreen.tsx': 10,
  'components/StudyRoomScreen.tsx': 11,
  'components/StudyWalletPanel.tsx': 23,
  'components/TestAnalysisModal.tsx': 6,
  'components/TestConfigModal.tsx': 75,
  'components/TestTakingScreen.tsx': 59,
  'components/TestUtilityToolbar.tsx': 10,
  'components/TurnstileWidget.tsx': 1,
  'components/UsernameRequiredModal.tsx': 17,
  'components/WalletModal.tsx': 1,
  'components/YouTubeEmbed.tsx': 1,
  'components/YoutubeTranscriptPanel.tsx': 6,
  'components/academic/CourseChips.tsx': 1,
  'components/academic/CourseMultiSelect.tsx': 9,
  'components/academic/CoursePicker.tsx': 10,
  'components/academic/ManageOutlineModal.tsx': 8,
  'components/academic/MoveToCourseModal.tsx': 3,
  'components/academic/TopicFilterChip.tsx': 1,
  'components/academic/TopicPicker.tsx': 12,
  'components/admin/AdminAI.tsx': 21,
  'components/admin/AdminAnalytics.tsx': 54,
  'components/admin/AdminAppeals.tsx': 6,
  'components/admin/AdminAudit.tsx': 5,
  'components/admin/AdminCommunications.tsx': 1,
  'components/admin/AdminContentModeration.tsx': 9,
  'components/admin/AdminJobs.tsx': 20,
  'components/admin/AdminMarketplace.tsx': 5,
  'components/admin/AdminOverview.tsx': 15,
  'components/admin/AdminProductFeatures.tsx': 18,
  'components/admin/AdminReports.tsx': 7,
  'components/admin/AdminShell.tsx': 3,
  'components/admin/AdminUsers.tsx': 2,
  'components/admin/ConfirmDialog.tsx': 2,
  'components/admin/PaginationBar.tsx': 1,
  'components/admin/UserDetailDrawer.tsx': 18,
  'components/budget/BudgetQuickLinks.tsx': 4,
  'components/chat/ChatHeader.tsx': 7,
  'components/chat/ChatHeaderMenu.tsx': 2,
  'components/chat/MessageList.tsx': 4,
  'components/chat/MessageReactions.tsx': 3,
  'components/chat/MessageRow.tsx': 2,
  'components/community/BoardComposer.tsx': 4,
  'components/community/BoardPostCard.tsx': 19,
  'components/community/BoardPostPanel.tsx': 12,
  'components/community/CommunityBoard.tsx': 17,
  'components/community/CommunityMembersPanel.tsx': 10,
  'components/community/CommunityTile.tsx': 2,
  'components/community/LegacyQuestionCard.tsx': 5,
  'components/community/RepostComposer.tsx': 6,
  'components/community/SavedPostsPanel.tsx': 9,
  'components/discover/DiscoverComingSoon.tsx': 3,
  'components/discover/DiscoverWorkspaceBar.tsx': 2,
  'components/discover/GroupDiscoverabilityFields.tsx': 9,
  'components/featureTips/FeatureTip.tsx': 5,
  'components/jobs/InterviewCalendarActions.tsx': 2,
  'components/jobs/JobApplicantDetailModal.tsx': 11,
  'components/jobs/JobApplicantNotes.tsx': 11,
  'components/jobs/JobBulkActionsBar.tsx': 8,
  'components/jobs/JobCompanyManageCard.tsx': 21,
  'components/jobs/JobEmployerInsights.tsx': 14,
  'components/jobs/JobHiringFunnelStrip.tsx': 2,
  'components/jobs/JobInterviewInvite.tsx': 10,
  'components/jobs/JobInterviewScheduler.tsx': 26,
  'components/jobs/JobMessageTemplatePicker.tsx': 1,
  'components/jobs/JobOfferCard.tsx': 15,
  'components/jobs/JobOfferPanel.tsx': 29,
  'components/jobs/JobPostingInsights.tsx': 7,
  'components/jobs/JobReportForm.tsx': 10,
  'components/jobs/JobSafetyTips.tsx': 2,
  'components/jobs/JobTrustBadge.tsx': 2,
  'components/jobs/JobsWorkspaceNav.tsx': 4,
  'components/jobs/ResumeUploadField.tsx': 8,
  'components/layout/AppShell.tsx': 17,
  'components/layout/Breadcrumb.tsx': 1,
  'components/library/LibraryRail.tsx': 11,
  'components/library/LibrarySearch.tsx': 14,
  'components/marketplace/CampusSearchSelect.tsx': 8,
  'components/marketplace/CourseBrowsePanel.tsx': 24,
  'components/marketplace/CreateBundleModal.tsx': 7,
  'components/marketplace/GuestMarketplaceShell.tsx': 1,
  'components/marketplace/ListingCard.tsx': 6,
  'components/marketplace/ListingClassifier.tsx': 24,
  'components/marketplace/MarketplaceBrowseTree.tsx': 2,
  'components/marketplace/MarketplaceFilterPanel.tsx': 3,
  'components/marketplace/MarketplaceSearchSuggest.tsx': 4,
  'components/marketplace/MarketplaceWorkspaceBar.tsx': 6,
  'components/marketplace/OpenDisputeModal.tsx': 9,
  'components/marketplace/OrderReceipt.tsx': 1,
  'components/marketplace/PublishQuestionBankModal.tsx': 21,
  'components/marketplace/PublishStudyPackModal.tsx': 19,
  'components/marketplace/SellerCampaignPanel.tsx': 4,
  'components/marketplace/SellerCouponsPanel.tsx': 7,
  'components/marketplace/SellerInsightsDrawer.tsx': 25,
  'components/marketplace/SellerOnboardingWizard.tsx': 6,
  'components/marketplace/SellerPayoutSetup.tsx': 8,
  'components/marketplace/UpdateStudyPackModal.tsx': 12,
  'components/moderation/AppealListingModal.tsx': 8,
  'components/moderation/ReportContentModal.tsx': 7,
  'components/moderation/RightsAttestationCheckbox.tsx': 2,
  'components/offline/OfflineBundleCard.tsx': 8,
  'components/onboarding/AcademicIdentityStep.tsx': 13,
  'components/pwa/InstallAppBanner.tsx': 3,
  'components/settings/AcademicSettingsSection.tsx': 16,
};

/**
 * Screens Wave T migrated. The lint asserts these are exactly at their
 * allowlisted count (0 unless noted above), so a later edit cannot quietly
 * reintroduce an off-scale size on a screen that is already clean.
 */
export const MIGRATED_FILES: ReadonlyArray<string> = [
  'components/DashboardScreen.tsx',
  'components/NotesScreen.tsx',
  'components/Sidebar.tsx',
  'components/StudyHubScreen.tsx',
  'components/TestReviewScreen.tsx',
  'components/dashboard/DashboardHero.tsx',
  'components/dashboard/DashboardQuickLinks.tsx',
  'components/dashboard/DashboardStatGrid.tsx',
  'components/dashboard/DashboardSummaryRow.tsx',
  'components/dashboard/GettingStartedChecklist.tsx',
  'components/dashboard/GroupPerformanceMultiSelect.tsx',
  'components/layout/BottomNav.tsx',
  'components/layout/MeScreen.tsx',
];
