/** Base URL for hosted legal pages (web). Mobile may open these or use in-app Legal screen. */
export const LEGAL_BASE_URL =
  (typeof process !== 'undefined' && process.env?.EXPO_PUBLIC_LEGAL_BASE_URL) ||
  'https://lanternstudy.app';

export type LegalDocumentId = 'privacy' | 'terms' | 'cookies';

export const LEGAL_PATHS: Record<LegalDocumentId, string> = {
  privacy: '/privacy',
  terms: '/terms',
  cookies: '/cookies',
};

export function getLegalPageUrl(doc: LegalDocumentId): string {
  const base = LEGAL_BASE_URL.replace(/\/$/, '');
  return `${base}${LEGAL_PATHS[doc]}`;
}

export const LEGAL_DOCUMENT_TITLES: Record<LegalDocumentId, string> = {
  privacy: 'Privacy Policy',
  terms: 'Terms of Service',
  cookies: 'Cookie Notice',
};

export const PRIVACY_POLICY_MD = `# Privacy Policy

**Last updated:** June 13, 2026

Lantern Study ("we", "us", "our") provides a collaborative study platform with flashcards, groups, tests, notes, marketplace listings, and AI-assisted features. This Privacy Policy explains how we collect, use, store, and share personal data when you use our web and mobile applications.

**Important:** This document is an engineering template prepared for operational readiness. Have qualified legal counsel review it before production launch in regulated markets.

## 1. Who we are

**Data controller:** Lantern Study  
**Contact:** privacy@lanternstudy.app

## 2. Data we collect

| Category | Examples | Source |
|----------|----------|--------|
| Account | Email, name, username, phone (optional), avatar | You / OAuth providers |
| Study content | Decks, flashcards, test results, notes, study activity | You |
| Social | Group membership, messages, direct messages | You |
| Marketplace | Listings, inquiries, images | You |
| AI usage | Feature used, provider, timestamps, rate-limit counters | Generated by use |
| Device | Push notification tokens (mobile), app version | Device |
| Technical | IP address, request logs, session tokens | Automatic |

We do not intentionally collect special category data (health, biometric, etc.).

## 3. How we use data

- Provide and improve the service (authentication, sync, notifications)
- Enable collaboration (groups, shared decks, study sessions)
- Operate AI features (generate content, tutor, companion chat, transcription)
- Enforce security (rate limits, abuse prevention, admin audit)
- Comply with legal obligations

**Legal bases (GDPR):** contract performance, legitimate interests (security, product improvement), consent where required (e.g. optional marketing if added later).

## 4. AI features and third-party AI providers

When you use AI features, relevant content (study notes, questions, audio for transcription, chat messages) may be sent to third-party AI providers to generate responses. Providers may include Groq, Google Gemini, Cloudflare Workers AI, and Hugging Face, selected automatically based on availability.

AI output may be inaccurate. Do not rely on AI for medical, legal, or other professional advice. See our [Terms of Service](/terms) and [AI System Card](https://lanternstudy.app/docs/ai-system-card).

We log AI inference metadata (feature, provider, timestamp) for rate limiting and auditability. We do not store full prompts in inference logs by default.

## 5. Third-party subprocessors

| Provider | Purpose | Data shared |
|----------|---------|-------------|
| Supabase | Database, auth, storage, realtime | Account and app data |
| AI providers | Inference | Prompt-related content |
| Google / Apple | OAuth sign-in | Profile identifiers |
| Sentry (optional) | Error monitoring | Technical diagnostics |
| Expo | Push notifications (mobile) | Device tokens |

See our subprocessor register in \`docs/compliance/subprocessors.md\` for the full list.

## 6. International transfers

Our infrastructure and subprocessors may process data in the United States and other countries. Where required, we rely on appropriate safeguards such as Standard Contractual Clauses.

## 7. Retention

| Data type | Retention |
|-----------|-----------|
| Account data | Until account deletion |
| AI inference logs | 90 days |
| Server logs | 30–90 days |
| Admin audit logs | 24 months (anonymized where possible after account deletion) |

## 8. Your rights (GDPR / UK GDPR)

You may request:

- **Access** — export your data (Settings → Export my data)
- **Erasure** — delete your account (Settings → Delete account)
- **Rectification** — update profile in Settings
- **Portability** — JSON export of your account data
- **Object / restrict** — contact privacy@lanternstudy.app

We respond within 30 days where applicable.

## 9. Security

We use encryption in transit (TLS), row-level security on database tables, authentication, rate limiting, and access controls. No method of transmission is 100% secure.

## 10. Children

Lantern Study is not directed at children under 16. We do not knowingly collect data from children.

## 11. Changes

We may update this policy. Material changes will be notified in-app or by email where appropriate.

## 12. Contact

Questions or data subject requests: **privacy@lanternstudy.app**
`;

export const TERMS_OF_SERVICE_MD = `# Terms of Service

**Last updated:** June 13, 2026

These Terms of Service ("Terms") govern your use of Lantern Study web and mobile applications ("Service"). By creating an account or using the Service, you agree to these Terms.

**Important:** This document is an engineering template. Have qualified legal counsel review it before production launch.

## 1. Eligibility

You must be at least 16 years old and able to form a binding contract. You are responsible for your account credentials.

## 2. Acceptable use

You agree not to:

- Violate laws or others' rights
- Upload malware, spam, or abusive content
- Attempt unauthorized access or scrape the Service at scale
- Use AI features to generate harmful, illegal, or deceptive content
- Misrepresent marketplace listings or engage in fraud

We may suspend or terminate accounts that violate these Terms.

## 3. Your content

You retain ownership of content you create (decks, notes, messages, listings). You grant us a limited license to host, process, and display your content solely to operate the Service, including AI features you invoke.

You are responsible for content you share in groups or the marketplace.

## 4. AI features

AI-generated flashcards, questions, explanations, and chat responses are provided **as-is** and may contain errors. AI output is **not professional advice**. You must review AI-generated study material before relying on it in academic or professional settings.

AI usage is subject to daily rate limits. We may change providers, models, or limits with reasonable notice where practicable.

## 5. Marketplace

Marketplace listings are user-generated and intended for **Nigerian campus communities** with **on-campus pickup**. Prices are shown in Nigerian Naira (₦). Payments are arranged directly between buyers and sellers unless we explicitly state otherwise.

You must be at least **16 years old** to buy or sell on the marketplace. You are responsible for meeting safely on campus, verifying items, and complying with your institution's rules.

We do not guarantee the quality, safety, or legality of items or services offered. Lantern Study is not a party to peer-to-peer transactions and does not provide payment processing for marketplace sales.

## 6. Privacy

Our [Privacy Policy](/privacy) describes how we handle personal data.

## 7. Account termination

You may delete your account at any time in Settings. We may terminate or suspend access for violations, legal requirements, or prolonged inactivity.

## 8. Disclaimers

THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.

## 9. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, LANTERN STUDY SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, OR GOODWILL.

## 10. Governing law

These Terms are governed by the laws applicable in your jurisdiction of residence where mandatory consumer protections apply, otherwise as specified by counsel during legal review.

## 11. Changes

We may update these Terms. Continued use after changes constitutes acceptance of the updated Terms.

## 12. Contact

**support@lanternstudy.app**
`;

export const COOKIE_NOTICE_MD = `# Cookie Notice

**Last updated:** June 13, 2026

This notice describes how Lantern Study uses cookies and similar technologies on the web application.

## What we use today

Lantern Study currently uses **essential** storage only:

| Name / storage | Type | Purpose | Duration |
|----------------|------|---------|----------|
| Supabase auth session | Local storage / cookie | Keep you signed in | Session / refresh token lifetime |
| \`theme\` | Local storage | Dark/light mode preference | Until cleared |
| \`ui-storage\` | Local storage | UI preferences (e.g. low-data mode) | Until cleared |

These are necessary for the Service to function. We do not use non-essential analytics or advertising cookies at this time.

## Mobile app

The mobile app stores session tokens and preferences in on-device storage (AsyncStorage), not browser cookies.

## Future changes

If we add analytics, marketing, or third-party embeds that set non-essential cookies, we will update this notice and, where required, request consent before setting those cookies.

## Contact

**privacy@lanternstudy.app**
`;

export const LEGAL_DOCUMENT_CONTENT: Record<LegalDocumentId, string> = {
  privacy: PRIVACY_POLICY_MD,
  terms: TERMS_OF_SERVICE_MD,
  cookies: COOKIE_NOTICE_MD,
};

export function getLegalDocumentContent(doc: LegalDocumentId): string {
  return LEGAL_DOCUMENT_CONTENT[doc];
}
