-- Expand Nigerian marketplace campuses (NUC universities + polytechnics + city "Other" options).
-- Idempotent via ON CONFLICT (slug).

INSERT INTO marketplace_campuses (name, city, state, country_code, slug) VALUES
  ('Abubakar Tafawa Balewa University', 'Bauchi', 'Bauchi', 'NG', 'abubakar-tafawa-balewa-university'),
  ('Ahmadu Bello University', 'Zaria', 'Kaduna', 'NG', 'ahmadu-bello-university'),
  ('Bayero University', 'Kano', 'Kano', 'NG', 'bayero-university'),
  ('Federal University Gashua', 'Gashua', 'Yobe', 'NG', 'federal-university-gashua'),
  ('Federal University of Petroleum Resources', 'Effurun', 'Delta', 'NG', 'federal-university-of-petroleum-resources'),
  ('Federal University of Technology, Akure', 'Akure', 'Ondo', 'NG', 'federal-university-of-technology-akure'),
  ('Federal University of Technology, Minna', 'Minna', 'Niger', 'NG', 'federal-university-of-technology-minna'),
  ('Federal University of Technology, Owerri', 'Owerri', 'Imo', 'NG', 'federal-university-of-technology-owerri'),
  ('Federal University Dutse', 'Dutse', 'Jigawa', 'NG', 'federal-university-dutse'),
  ('Federal University Dutsin-Ma', 'Dutsin-Ma', 'Katsina', 'NG', 'federal-university-dutsin-ma'),
  ('Federal University Kashere', 'Kashere', 'Gombe', 'NG', 'federal-university-kashere'),
  ('Federal University Lafia', 'Lafia', 'Nasarawa', 'NG', 'federal-university-lafia'),
  ('Federal University Lokoja', 'Lokoja', 'Kogi', 'NG', 'federal-university-lokoja'),
  ('Alex Ekwueme Federal University Ndufu-Alike', 'Ndufu-Alike', 'Ebonyi', 'NG', 'alex-ekwueme-federal-university-ndufu-alike'),
  ('Federal University Otuoke', 'Otuoke', 'Bayelsa', 'NG', 'federal-university-otuoke'),
  ('Federal University Oye-Ekiti', 'Oye-Ekiti', 'Ekiti', 'NG', 'federal-university-oye-ekiti'),
  ('Federal University Wukari', 'Wukari', 'Taraba', 'NG', 'federal-university-wukari'),
  ('Federal University Birnin Kebbi', 'Birnin Kebbi', 'Kebbi', 'NG', 'federal-university-birnin-kebbi'),
  ('Federal University Gusau', 'Gusau', 'Zamfara', 'NG', 'federal-university-gusau'),
  ('Michael Okpara University of Agriculture', 'Umudike', 'Abia', 'NG', 'michael-okpara-university-of-agriculture'),
  ('Modibbo Adama University', 'Yola', 'Adamawa', 'NG', 'modibbo-adama-university'),
  ('National Open University of Nigeria', 'Abuja', 'FCT', 'NG', 'national-open-university-of-nigeria'),
  ('Nigeria Police Academy', 'Wudil', 'Kano', 'NG', 'nigeria-police-academy'),
  ('Nigerian Defence Academy', 'Kaduna', 'Kaduna', 'NG', 'nigerian-defence-academy'),
  ('Nnamdi Azikiwe University', 'Awka', 'Anambra', 'NG', 'nnamdi-azikiwe-university'),
  ('Obafemi Awolowo University', 'Ile-Ife', 'Osun', 'NG', 'obafemi-awolowo-university'),
  ('University of Abuja', 'Gwagwalada', 'FCT', 'NG', 'university-of-abuja'),
  ('Federal University of Agriculture, Abeokuta', 'Abeokuta', 'Ogun', 'NG', 'federal-university-of-agriculture-abeokuta'),
  ('Joseph Sarwuan Tarka University', 'Makurdi', 'Benue', 'NG', 'joseph-sarwuan-tarka-university'),
  ('University of Benin', 'Benin City', 'Edo', 'NG', 'university-of-benin'),
  ('University of Calabar', 'Calabar', 'Cross River', 'NG', 'university-of-calabar'),
  ('University of Ibadan', 'Ibadan', 'Oyo', 'NG', 'university-of-ibadan'),
  ('University of Ilorin', 'Ilorin', 'Kwara', 'NG', 'university-of-ilorin'),
  ('University of Jos', 'Jos', 'Plateau', 'NG', 'university-of-jos'),
  ('University of Lagos', 'Lagos', 'Lagos', 'NG', 'university-of-lagos'),
  ('University of Maiduguri', 'Maiduguri', 'Borno', 'NG', 'university-of-maiduguri'),
  ('University of Nigeria, Nsukka', 'Nsukka', 'Enugu', 'NG', 'university-of-nigeria-nsukka'),
  ('University of Port Harcourt', 'Port Harcourt', 'Rivers', 'NG', 'university-of-port-harcourt'),
  ('University of Uyo', 'Uyo', 'Akwa Ibom', 'NG', 'university-of-uyo'),
  ('Usmanu Danfodiyo University', 'Sokoto', 'Sokoto', 'NG', 'usmanu-danfodiyo-university'),
  ('Nigerian Maritime University', 'Okerenkoko', 'Delta', 'NG', 'nigerian-maritime-university'),
  ('Air Force Institute of Technology', 'Kaduna', 'Kaduna', 'NG', 'air-force-institute-of-technology'),
  ('Nigerian Army University', 'Biu', 'Borno', 'NG', 'nigerian-army-university'),
  ('Federal University of Health Sciences, Otukpo', 'Otukpo', 'Benue', 'NG', 'federal-university-of-health-sciences-otukpo'),
  ('Federal University of Agriculture, Zuru', 'Zuru', 'Kebbi', 'NG', 'federal-university-of-agriculture-zuru'),
  ('Federal University of Technology, Babura', 'Babura', 'Jigawa', 'NG', 'federal-university-of-technology-babura'),
  ('Federal University of Technology, Ikot Abasi', 'Ikot Abasi', 'Akwa Ibom', 'NG', 'federal-university-of-technology-ikot-abasi'),
  ('Federal University of Health Sciences, Azare', 'Azare', 'Bauchi', 'NG', 'federal-university-of-health-sciences-azare'),
  ('Federal University of Health Sciences, Ila Orangun', 'Ila Orangun', 'Osun', 'NG', 'federal-university-of-health-sciences-ila-orangun'),
  ('David Umahi Federal University of Medical Sciences', 'Uburu', 'Ebonyi', 'NG', 'david-umahi-federal-university-of-medical-sciences'),
  ('Admiralty University', 'Ibusa', 'Delta', 'NG', 'admiralty-university'),
  ('Federal University of Transportation', 'Daura', 'Katsina', 'NG', 'federal-university-of-transportation'),
  ('African Aviation and Aerospace University', 'Abuja', 'FCT', 'NG', 'african-aviation-and-aerospace-university'),
  ('National University of Science and Technology', 'Abuja', 'FCT', 'NG', 'national-university-of-science-and-technology'),
  ('Federal University of Agriculture, Bassambiri', 'Bassambiri', 'Bayelsa', 'NG', 'federal-university-of-agriculture-bassambiri'),
  ('Federal University of Health Sciences, Kwale', 'Kwale', 'Delta', 'NG', 'federal-university-of-health-sciences-kwale'),
  ('Federal University of Health Sciences, Katsina', 'Katsina', 'Katsina', 'NG', 'federal-university-of-health-sciences-katsina'),
  ('Federal University of Agriculture, Mubi', 'Mubi', 'Adamawa', 'NG', 'federal-university-of-agriculture-mubi'),
  ('Federal University of Education, Zaria', 'Zaria', 'Kaduna', 'NG', 'federal-university-of-education-zaria'),
  ('Alvan Ikoku Federal University of Education', 'Owerri', 'Imo', 'NG', 'alvan-ikoku-federal-university-of-education'),
  ('Yusuf Maitama Sule Federal University of Education', 'Kano', 'Kano', 'NG', 'yusuf-maitama-sule-federal-university-of-education'),
  ('Adeyemi Federal University of Education', 'Ondo', 'Ondo', 'NG', 'adeyemi-federal-university-of-education'),
  ('Federal University of Allied Health Sciences', 'Enugu', 'Enugu', 'NG', 'federal-university-of-allied-health-sciences'),
  ('Federal University of Medicine and Medical Sciences', 'Abeokuta', 'Ogun', 'NG', 'federal-university-of-medicine-and-medical-sciences'),
  ('Federal University of Education, Pankshin', 'Pankshin', 'Plateau', 'NG', 'federal-university-of-education-pankshin'),
  ('Federal University of Education, Kontagora', 'Kontagora', 'Niger', 'NG', 'federal-university-of-education-kontagora'),
  ('University of Maritime Studies', 'Oron', 'Akwa Ibom', 'NG', 'university-of-maritime-studies'),
  ('Federal University of Environment and Technology', 'Tai', 'Rivers', 'NG', 'federal-university-of-environment-and-technology'),
  ('Federal University of Applied Sciences', 'Kachia', 'Kaduna', 'NG', 'federal-university-of-applied-sciences'),
  ('Tai Solarin Federal University of Education', 'Ijagun', 'Ogun', 'NG', 'tai-solarin-federal-university-of-education'),
  ('Federal University of Agriculture and Developmental Studies', 'Iragbiji', 'Osun', 'NG', 'federal-university-of-agriculture-and-developmental-studies'),
  ('Federal University of Technology and Environmental Studies', 'Iyin-Ekiti', 'Ekiti', 'NG', 'federal-university-of-technology-and-environmental-studies'),
  ('Federal University of Agriculture and Technology, Okeho', 'Okeho', 'Oyo', 'NG', 'federal-university-of-agriculture-and-technology-okeho'),
  ('Federal University of Health Science and Technology', 'Tsafe', 'Zamfara', 'NG', 'federal-university-of-health-science-and-technology'),
  ('Federal University of Agriculture and Technology, Obio-Akpa', 'Obio-Akpa', 'Akwa Ibom', 'NG', 'federal-university-of-agriculture-and-technology-obio-akpa'),
  ('Federal University of Science and Technology, Epe', 'Epe', 'Lagos', 'NG', 'federal-university-of-science-and-technology-epe'),
  ('Federal University of Science and Technology, Kabo', 'Kabo', 'Kano', 'NG', 'federal-university-of-science-and-technology-kabo'),
  ('Rivers State University', 'Port Harcourt', 'Rivers', 'NG', 'rivers-state-university'),
  ('Ambrose Alli University', 'Ekpoma', 'Edo', 'NG', 'ambrose-alli-university'),
  ('Abia State University', 'Uturu', 'Abia', 'NG', 'abia-state-university'),
  ('Ekiti State University', 'Ado-Ekiti', 'Ekiti', 'NG', 'ekiti-state-university'),
  ('Enugu State University of Science and Technology', 'Enugu', 'Enugu', 'NG', 'enugu-state-university-of-science-and-technology'),
  ('Olabisi Onabanjo University', 'Ago-Iwoye', 'Ogun', 'NG', 'olabisi-onabanjo-university'),
  ('Lagos State University', 'Ojo', 'Lagos', 'NG', 'lagos-state-university'),
  ('Ladoke Akintola University of Technology', 'Ogbomoso', 'Oyo', 'NG', 'ladoke-akintola-university-of-technology'),
  ('Benue State University', 'Makurdi', 'Benue', 'NG', 'benue-state-university'),
  ('Delta State University', 'Abraka', 'Delta', 'NG', 'delta-state-university'),
  ('Imo State University', 'Owerri', 'Imo', 'NG', 'imo-state-university'),
  ('Adekunle Ajasin University', 'Akungba', 'Ondo', 'NG', 'adekunle-ajasin-university'),
  ('Prince Abubakar Audu University', 'Anyigba', 'Kogi', 'NG', 'prince-abubakar-audu-university'),
  ('Chukwuemeka Odumegwu Ojukwu University', 'Uli', 'Anambra', 'NG', 'chukwuemeka-odumegwu-ojukwu-university'),
  ('Ebonyi State University', 'Abakaliki', 'Ebonyi', 'NG', 'ebonyi-state-university'),
  ('Aliko Dangote University of Science and Technology', 'Wudil', 'Kano', 'NG', 'aliko-dangote-university-of-science-and-technology'),
  ('Niger Delta University', 'Yenagoa', 'Bayelsa', 'NG', 'niger-delta-university'),
  ('Adamawa State University', 'Mubi', 'Adamawa', 'NG', 'adamawa-state-university'),
  ('Nasarawa State University', 'Keffi', 'Nasarawa', 'NG', 'nasarawa-state-university'),
  ('University of Cross River State', 'Calabar', 'Cross River', 'NG', 'university-of-cross-river-state'),
  ('Gombe State University', 'Gombe', 'Gombe', 'NG', 'gombe-state-university'),
  ('Kaduna State University', 'Kaduna', 'Kaduna', 'NG', 'kaduna-state-university'),
  ('Ibrahim Badamasi Babangida University', 'Lapai', 'Niger', 'NG', 'ibrahim-badamasi-babangida-university'),
  ('Plateau State University', 'Bokkos', 'Plateau', 'NG', 'plateau-state-university'),
  ('Yobe State University', 'Damaturu', 'Yobe', 'NG', 'yobe-state-university'),
  ('Kebbi State University of Science and Technology', 'Aliero', 'Kebbi', 'NG', 'kebbi-state-university-of-science-and-technology'),
  ('Umaru Musa Yar''adua University', 'Katsina', 'Katsina', 'NG', 'umaru-musa-yar-adua-university'),
  ('Osun State University', 'Osogbo', 'Osun', 'NG', 'osun-state-university'),
  ('Olusegun Agagu University of Science and Technology', 'Okitipupa', 'Ondo', 'NG', 'olusegun-agagu-university-of-science-and-technology'),
  ('Taraba State University', 'Jalingo', 'Taraba', 'NG', 'taraba-state-university'),
  ('Kwara State University', 'Malete', 'Kwara', 'NG', 'kwara-state-university'),
  ('Sokoto State University', 'Sokoto', 'Sokoto', 'NG', 'sokoto-state-university'),
  ('Akwa Ibom State University', 'Ikot Akpaden', 'Akwa Ibom', 'NG', 'akwa-ibom-state-university'),
  ('Ignatius Ajuru University of Education', 'Port Harcourt', 'Rivers', 'NG', 'ignatius-ajuru-university-of-education'),
  ('Bauchi State University', 'Gadau', 'Bauchi', 'NG', 'bauchi-state-university'),
  ('Northwest University', 'Kano', 'Kano', 'NG', 'northwest-university'),
  ('First Technical University', 'Ibadan', 'Oyo', 'NG', 'first-technical-university'),
  ('Sule Lamido University', 'Kafin Hausa', 'Jigawa', 'NG', 'sule-lamido-university'),
  ('University of Medical Sciences', 'Ondo', 'Ondo', 'NG', 'university-of-medical-sciences'),
  ('Edo State University', 'Iyamho', 'Edo', 'NG', 'edo-state-university'),
  ('Kingsley Ozumba Mbadiwe University', 'Ogboko', 'Imo', 'NG', 'kingsley-ozumba-mbadiwe-university'),
  ('University of Africa', 'Toru-Orua', 'Bayelsa', 'NG', 'university-of-africa'),
  ('Kashim Ibrahim University', 'Maiduguri', 'Borno', 'NG', 'kashim-ibrahim-university'),
  ('Moshood Abiola University of Science and Technology', 'Abeokuta', 'Ogun', 'NG', 'moshood-abiola-university-of-science-and-technology'),
  ('Zamfara State University', 'Talata Mafara', 'Zamfara', 'NG', 'zamfara-state-university'),
  ('Bayelsa Medical University', 'Yenagoa', 'Bayelsa', 'NG', 'bayelsa-medical-university'),
  ('University of Agriculture and Environmental Sciences', 'Umuagwo', 'Imo', 'NG', 'university-of-agriculture-and-environmental-sciences'),
  ('Confluence University of Science and Technology', 'Osara', 'Kogi', 'NG', 'confluence-university-of-science-and-technology'),
  ('Bamidele Olumilua University of Education, Science and Technology', 'Ikere', 'Ekiti', 'NG', 'bamidele-olumilua-university-of-education-science-and-technology'),
  ('University of Delta', 'Agbor', 'Delta', 'NG', 'university-of-delta'),
  ('Delta University of Science and Technology', 'Ozoro', 'Delta', 'NG', 'delta-university-of-science-and-technology'),
  ('Dennis Osadebay University', 'Asaba', 'Delta', 'NG', 'dennis-osadebay-university'),
  ('Lagos State University of Education', 'Ijanikin', 'Lagos', 'NG', 'lagos-state-university-of-education'),
  ('Lagos State University of Science and Technology', 'Ikorodu', 'Lagos', 'NG', 'lagos-state-university-of-science-and-technology'),
  ('Shehu Shagari University of Education', 'Sokoto', 'Sokoto', 'NG', 'shehu-shagari-university-of-education'),
  ('State University of Medical and Applied Sciences', 'Igbo-Eno', 'Enugu', 'NG', 'state-university-of-medical-and-applied-sciences'),
  ('University of Ilesa', 'Ilesa', 'Osun', 'NG', 'university-of-ilesa'),
  ('Emmanuel Alayande University of Education', 'Oyo', 'Oyo', 'NG', 'emmanuel-alayande-university-of-education'),
  ('Kogi State University', 'Kabba', 'Kogi', 'NG', 'kogi-state-university'),
  ('AbdulKadir Kure University', 'Minna', 'Niger', 'NG', 'abdulkadir-kure-university'),
  ('Kwara State University of Education', 'Ilorin', 'Kwara', 'NG', 'kwara-state-university-of-education'),
  ('Abdulsalam Abubakar University of Agriculture and Climate Action', 'Mokwa', 'Niger', 'NG', 'abdulsalam-abubakar-university-of-agriculture-and-climate-action'),
  ('Ebonyi State University of ICT, Science and Technology', 'Oferekpe', 'Ebonyi', 'NG', 'ebonyi-state-university-of-ict-science-and-technology'),
  ('Cross River University of Education and Entrepreneurship', 'Akamkpa', 'Cross River', 'NG', 'cross-river-university-of-education-and-entrepreneurship'),
  ('Benue State University of Agriculture, Science and Technology', 'Ihugh', 'Benue', 'NG', 'benue-state-university-of-agriculture-science-and-technology'),
  ('University of Aeronautics and Aerospace Engineering', 'Ezza', 'Ebonyi', 'NG', 'university-of-aeronautics-and-aerospace-engineering'),
  ('University of Innovation, Science and Technology', 'Omuma', 'Imo', 'NG', 'university-of-innovation-science-and-technology'),
  ('Babcock University', 'Ilishan-Remo', 'Ogun', 'NG', 'babcock-university'),
  ('Igbinedion University', 'Okada', 'Edo', 'NG', 'igbinedion-university'),
  ('Madonna University', 'Okija', 'Anambra', 'NG', 'madonna-university'),
  ('Bowen University', 'Iwo', 'Osun', 'NG', 'bowen-university'),
  ('Benson Idahosa University', 'Benin City', 'Edo', 'NG', 'benson-idahosa-university'),
  ('Covenant University', 'Ota', 'Ogun', 'NG', 'covenant-university'),
  ('Pan-Atlantic University', 'Lekki', 'Lagos', 'NG', 'pan-atlantic-university'),
  ('American University of Nigeria', 'Yola', 'Adamawa', 'NG', 'american-university-of-nigeria'),
  ('Ajayi Crowther University', 'Oyo', 'Oyo', 'NG', 'ajayi-crowther-university'),
  ('Al-Hikmah University', 'Ilorin', 'Kwara', 'NG', 'al-hikmah-university'),
  ('Al-Qalam University', 'Katsina', 'Katsina', 'NG', 'al-qalam-university'),
  ('Bells University of Technology', 'Ota', 'Ogun', 'NG', 'bells-university-of-technology'),
  ('Bingham University', 'Karu', 'Nasarawa', 'NG', 'bingham-university'),
  ('Caritas University', 'Enugu', 'Enugu', 'NG', 'caritas-university'),
  ('Crawford University', 'Igbesa', 'Ogun', 'NG', 'crawford-university'),
  ('Crescent University', 'Abeokuta', 'Ogun', 'NG', 'crescent-university'),
  ('Kwararafa University', 'Wukari', 'Taraba', 'NG', 'kwararafa-university'),
  ('Lead City University', 'Ibadan', 'Oyo', 'NG', 'lead-city-university'),
  ('Novena University', 'Ogume', 'Delta', 'NG', 'novena-university'),
  ('Redeemer''s University', 'Ede', 'Osun', 'NG', 'redeemer-s-university'),
  ('Renaissance University', 'Enugu', 'Enugu', 'NG', 'renaissance-university'),
  ('University of Mkar', 'Mkar', 'Benue', 'NG', 'university-of-mkar'),
  ('Joseph Ayo Babalola University', 'Ikeji-Arakeji', 'Osun', 'NG', 'joseph-ayo-babalola-university'),
  ('Achievers University', 'Owo', 'Ondo', 'NG', 'achievers-university'),
  ('Caleb University', 'Imota', 'Lagos', 'NG', 'caleb-university'),
  ('Fountain University', 'Osogbo', 'Osun', 'NG', 'fountain-university'),
  ('African University of Science and Technology', 'Abuja', 'FCT', 'NG', 'african-university-of-science-and-technology'),
  ('Obong University', 'Obong Ntak', 'Akwa Ibom', 'NG', 'obong-university'),
  ('Salem University', 'Lokoja', 'Kogi', 'NG', 'salem-university'),
  ('Tansian University', 'Umunya', 'Anambra', 'NG', 'tansian-university'),
  ('Veritas University', 'Abuja', 'FCT', 'NG', 'veritas-university'),
  ('Wesley University', 'Ondo', 'Ondo', 'NG', 'wesley-university'),
  ('Western Delta University', 'Oghara', 'Delta', 'NG', 'western-delta-university'),
  ('Afe Babalola University', 'Ado-Ekiti', 'Ekiti', 'NG', 'afe-babalola-university'),
  ('Godfrey Okoye University', 'Enugu', 'Enugu', 'NG', 'godfrey-okoye-university'),
  ('Nile University of Nigeria', 'Abuja', 'FCT', 'NG', 'nile-university-of-nigeria'),
  ('Oduduwa University', 'Ipetumodu', 'Osun', 'NG', 'oduduwa-university'),
  ('Paul University', 'Awka', 'Anambra', 'NG', 'paul-university'),
  ('Rhema University', 'Obeama-Asa', 'Rivers', 'NG', 'rhema-university'),
  ('Wellspring University', 'Evbuobanosa', 'Edo', 'NG', 'wellspring-university'),
  ('Adeleke University', 'Ede', 'Osun', 'NG', 'adeleke-university'),
  ('Baze University', 'Abuja', 'FCT', 'NG', 'baze-university'),
  ('Landmark University', 'Omu-Aran', 'Kwara', 'NG', 'landmark-university'),
  ('Glorious Vision University', 'Ogwa', 'Edo', 'NG', 'glorious-vision-university'),
  ('Elizade University', 'Ilara-Mokin', 'Ondo', 'NG', 'elizade-university'),
  ('Evangel University', 'Akaeze', 'Ebonyi', 'NG', 'evangel-university'),
  ('Gregory University', 'Uturu', 'Abia', 'NG', 'gregory-university'),
  ('McPherson University', 'Seriki Sotayo', 'Ogun', 'NG', 'mcpherson-university'),
  ('Southwestern University', 'Okun Owa', 'Ogun', 'NG', 'southwestern-university'),
  ('Augustine University', 'Ilara', 'Lagos', 'NG', 'augustine-university'),
  ('Chrisland University', 'Abeokuta', 'Ogun', 'NG', 'chrisland-university'),
  ('Edwin Clark University', 'Kaigbodo', 'Delta', 'NG', 'edwin-clark-university'),
  ('Hallmark University', 'Ijebu-Itele', 'Ogun', 'NG', 'hallmark-university'),
  ('Hezekiah University', 'Umudi', 'Imo', 'NG', 'hezekiah-university'),
  ('Kings University', 'Ode-Omu', 'Osun', 'NG', 'kings-university'),
  ('Michael and Cecilia Ibru University', 'Agbarha-Otor', 'Delta', 'NG', 'michael-and-cecilia-ibru-university'),
  ('Mountain Top University', 'Makogi-Oba', 'Ogun', 'NG', 'mountain-top-university'),
  ('Ritman University', 'Ikot Ekpene', 'Akwa Ibom', 'NG', 'ritman-university'),
  ('Summit University', 'Offa', 'Kwara', 'NG', 'summit-university'),
  ('Christopher University', 'Mowe', 'Ogun', 'NG', 'christopher-university'),
  ('Kola Daisi University', 'Ibadan', 'Oyo', 'NG', 'kola-daisi-university'),
  ('Anchor University', 'Ayobo', 'Lagos', 'NG', 'anchor-university'),
  ('Dominican University', 'Ibadan', 'Oyo', 'NG', 'dominican-university'),
  ('Legacy University', 'Okija', 'Anambra', 'NG', 'legacy-university'),
  ('Arthur Jarvis University', 'Akpabuyo', 'Cross River', 'NG', 'arthur-jarvis-university'),
  ('Ojaja University', 'Eiyenkorin', 'Kwara', 'NG', 'ojaja-university'),
  ('Coal City University', 'Enugu', 'Enugu', 'NG', 'coal-city-university'),
  ('Clifford University', 'Owerrinta', 'Abia', 'NG', 'clifford-university'),
  ('Spiritan University', 'Nneochi', 'Abia', 'NG', 'spiritan-university'),
  ('Precious Cornerstone University', 'Oyo', 'Oyo', 'NG', 'precious-cornerstone-university'),
  ('PAMO University of Medical Sciences', 'Port Harcourt', 'Rivers', 'NG', 'pamo-university-of-medical-sciences'),
  ('Atiba University', 'Oyo', 'Oyo', 'NG', 'atiba-university'),
  ('Eko University of Medical and Health Sciences', 'Ijanikin', 'Lagos', 'NG', 'eko-university-of-medical-and-health-sciences'),
  ('Skyline University', 'Kano', 'Kano', 'NG', 'skyline-university'),
  ('Greenfield University', 'Kaduna', 'Kaduna', 'NG', 'greenfield-university'),
  ('Dominion University', 'Ibadan', 'Oyo', 'NG', 'dominion-university'),
  ('Trinity University', 'Yaba', 'Lagos', 'NG', 'trinity-university'),
  ('Westland University', 'Iwo', 'Osun', 'NG', 'westland-university'),
  ('Topfaith University', 'Mkpatak', 'Akwa Ibom', 'NG', 'topfaith-university'),
  ('Thomas Adewumi University', 'Oko-Irese', 'Kwara', 'NG', 'thomas-adewumi-university'),
  ('Maranatha University', 'Lagos', 'Lagos', 'NG', 'maranatha-university'),
  ('Ave Maria University', 'Piyanko', 'Nasarawa', 'NG', 'ave-maria-university'),
  ('Al-Istiqama University', 'Sumaila', 'Kano', 'NG', 'al-istiqama-university'),
  ('Mudiame University', 'Irrua', 'Edo', 'NG', 'mudiame-university'),
  ('Havilla University', 'Nde-Ikom', 'Cross River', 'NG', 'havilla-university'),
  ('Claretian University of Nigeria', 'Nekede', 'Imo', 'NG', 'claretian-university-of-nigeria'),
  ('Karl-Kumm University', 'Vom', 'Plateau', 'NG', 'karl-kumm-university'),
  ('James Hope University', 'Lekki', 'Lagos', 'NG', 'james-hope-university'),
  ('Maryam Abacha American University of Nigeria', 'Kano', 'Kano', 'NG', 'maryam-abacha-american-university-of-nigeria'),
  ('Capital City University', 'Kano', 'Kano', 'NG', 'capital-city-university'),
  ('Ahman Pategi University', 'Patigi', 'Kwara', 'NG', 'ahman-pategi-university'),
  ('University of Offa', 'Offa', 'Kwara', 'NG', 'university-of-offa'),
  ('Mewar International University', 'Masaka', 'Nasarawa', 'NG', 'mewar-international-university'),
  ('Edusoko University', 'Bida', 'Niger', 'NG', 'edusoko-university'),
  ('Philomath University', 'Kuje', 'FCT', 'NG', 'philomath-university'),
  ('Khadija University', 'Majia', 'Jigawa', 'NG', 'khadija-university'),
  ('ANAN University', 'Kwall', 'Plateau', 'NG', 'anan-university'),
  ('North Eastern University', 'Gombe', 'Gombe', 'NG', 'north-eastern-university'),
  ('Al-Ansar University', 'Maiduguri', 'Borno', 'NG', 'al-ansar-university'),
  ('Margaret Lawrence University', 'Umunede', 'Delta', 'NG', 'margaret-lawrence-university'),
  ('Khalifa Isiyaku Rabiu University', 'Kano', 'Kano', 'NG', 'khalifa-isiyaku-rabiu-university'),
  ('Sports University', 'Idumuje-Ugboko', 'Delta', 'NG', 'sports-university'),
  ('Baba Ahmed University', 'Kano', 'Kano', 'NG', 'baba-ahmed-university'),
  ('Saisa University of Medical Sciences and Technology', 'Sokoto', 'Sokoto', 'NG', 'saisa-university-of-medical-sciences-and-technology'),
  ('Nigerian British University', 'Asa', 'Abia', 'NG', 'nigerian-british-university'),
  ('Peter University', 'Achina-Onneh', 'Anambra', 'NG', 'peter-university'),
  ('Newgate University', 'Minna', 'Niger', 'NG', 'newgate-university'),
  ('European University of Nigeria', 'Duboyi', 'FCT', 'NG', 'european-university-of-nigeria'),
  ('Northwest University Sokoto', 'Sokoto', 'Sokoto', 'NG', 'northwest-university-sokoto'),
  ('Rayhaan University', 'Birnin Kebbi', 'Kebbi', 'NG', 'rayhaan-university'),
  ('Muhammad Kamalud-Deen University', 'Ilorin', 'Kwara', 'NG', 'muhammad-kamalud-deen-university'),
  ('Sam Maris University', 'Supare', 'Ondo', 'NG', 'sam-maris-university'),
  ('Aletheia University', 'Ago-Iwoye', 'Ogun', 'NG', 'aletheia-university'),
  ('Lux Mundi University', 'Umuahia', 'Abia', 'NG', 'lux-mundi-university'),
  ('Maduka University', 'Ekwegbe', 'Enugu', 'NG', 'maduka-university'),
  ('Peaceland University', 'Enugu', 'Enugu', 'NG', 'peaceland-university'),
  ('Amadeus University', 'Amizi', 'Abia', 'NG', 'amadeus-university'),
  ('Vision University', 'Ikogbo', 'Ogun', 'NG', 'vision-university'),
  ('Azman University', 'Kano', 'Kano', 'NG', 'azman-university'),
  ('Huda University', 'Gusau', 'Zamfara', 'NG', 'huda-university'),
  ('Franco British International University', 'Kaduna', 'Kaduna', 'NG', 'franco-british-international-university'),
  ('Canadian University of Nigeria', 'Abuja', 'FCT', 'NG', 'canadian-university-of-nigeria'),
  ('Gerar University of Medical Science', 'Imope-Ijebu', 'Ogun', 'NG', 'gerar-university-of-medical-science'),
  ('British Canadian University', 'Obudu', 'Cross River', 'NG', 'british-canadian-university'),
  ('Hensard University', 'Toru-Orua', 'Bayelsa', 'NG', 'hensard-university'),
  ('Amaj University', 'Kwali', 'FCT', 'NG', 'amaj-university'),
  ('Phoenix University', 'Agwada', 'Nasarawa', 'NG', 'phoenix-university'),
  ('Wigwe University', 'Isiokpo', 'Rivers', 'NG', 'wigwe-university'),
  ('Hillside University of Science and Technology', 'Okemesi', 'Ekiti', 'NG', 'hillside-university-of-science-and-technology'),
  ('University on the Niger', 'Umunya', 'Anambra', 'NG', 'university-on-the-niger'),
  ('Elrazi Medical University', 'Yargaya', 'Kano', 'NG', 'elrazi-medical-university'),
  ('Venite University', 'Iloro-Ekiti', 'Ekiti', 'NG', 'venite-university'),
  ('Shanahan University', 'Onitsha', 'Anambra', 'NG', 'shanahan-university'),
  ('The Duke Medical University', 'Calabar', 'Cross River', 'NG', 'the-duke-medical-university'),
  ('Mercy Medical University', 'Iwo', 'Osun', 'NG', 'mercy-medical-university'),
  ('Cosmopolitan University', 'Abuja', 'FCT', 'NG', 'cosmopolitan-university'),
  ('Miva Open University', 'Abuja', 'FCT', 'NG', 'miva-open-university'),
  ('Iconic Open University', 'Sokoto', 'Sokoto', 'NG', 'iconic-open-university'),
  ('West Midlands Open University', 'Ibadan', 'Oyo', 'NG', 'west-midlands-open-university'),
  ('Al-Muhibbah Open University', 'Abuja', 'FCT', 'NG', 'al-muhibbah-open-university'),
  ('El-Amin University', 'Minna', 'Niger', 'NG', 'el-amin-university'),
  ('College of Petroleum and Energy Studies', 'Kaduna', 'Kaduna', 'NG', 'college-of-petroleum-and-energy-studies'),
  ('Jewel University', 'Gombe', 'Gombe', 'NG', 'jewel-university'),
  ('Prime University', 'Kuje', 'FCT', 'NG', 'prime-university'),
  ('Nigerian University of Technology and Management', 'Apapa', 'Lagos', 'NG', 'nigerian-university-of-technology-and-management'),
  ('Al-Bayan University', 'Ankpa', 'Kogi', 'NG', 'al-bayan-university'),
  ('Lighthouse University', 'Evbobanosa', 'Edo', 'NG', 'lighthouse-university'),
  ('African University of Economics', 'Abuja', 'FCT', 'NG', 'african-university-of-economics'),
  ('New City University', 'Ayetoro', 'Ogun', 'NG', 'new-city-university'),
  ('University of Fortune', 'Igbotako', 'Ondo', 'NG', 'university-of-fortune'),
  ('Eranova University', 'Abuja', 'FCT', 'NG', 'eranova-university'),
  ('Minaret University', 'Ikirun', 'Osun', 'NG', 'minaret-university'),
  ('Abdulrasaq Abubakar Toyin University', 'Ilorin', 'Kwara', 'NG', 'abdulrasaq-abubakar-toyin-university'),
  ('Southern Atlantic University', 'Uyo', 'Akwa Ibom', 'NG', 'southern-atlantic-university'),
  ('Lens University', 'Ilemona', 'Kwara', 'NG', 'lens-university'),
  ('Monarch University', 'Iyesi-Ota', 'Ogun', 'NG', 'monarch-university'),
  ('Tonine Iredia University of Communication', 'Benin City', 'Edo', 'NG', 'tonine-iredia-university-of-communication'),
  ('Isaac Balami University of Aeronautics and Management', 'Lagos', 'Lagos', 'NG', 'isaac-balami-university-of-aeronautics-and-management'),
  ('Kevin Eze University', 'Mgbowo', 'Enugu', 'NG', 'kevin-eze-university'),
  ('Tazkiyah University', 'Kaduna', 'Kaduna', 'NG', 'tazkiyah-university'),
  ('Leadership University', 'Abuja', 'FCT', 'NG', 'leadership-university'),
  ('Jimoh Babalola University', 'Ilorin', 'Kwara', 'NG', 'jimoh-babalola-university'),
  ('Bridget University', 'Mbaise', 'Imo', 'NG', 'bridget-university'),
  ('Greenland University', 'Jalingo', 'Taraba', 'NG', 'greenland-university'),
  ('JEFAP University', 'Suleja', 'Niger', 'NG', 'jefap-university'),
  ('Azione Verde University', 'Amaigbo', 'Imo', 'NG', 'azione-verde-university'),
  ('Unique Open University', 'Ojo', 'Lagos', 'NG', 'unique-open-university'),
  ('American Open University', 'Abeokuta', 'Ogun', 'NG', 'american-open-university'),
  ('Yaba College of Technology', 'Yaba', 'Lagos', 'NG', 'yaba-college-of-technology'),
  ('Federal Polytechnic, Ilaro', 'Ilaro', 'Ogun', 'NG', 'federal-polytechnic-ilaro'),
  ('Federal Polytechnic, Nekede', 'Nekede', 'Imo', 'NG', 'federal-polytechnic-nekede'),
  ('Federal Polytechnic, Ado-Ekiti', 'Ado-Ekiti', 'Ekiti', 'NG', 'federal-polytechnic-ado-ekiti'),
  ('Auchi Polytechnic', 'Auchi', 'Edo', 'NG', 'auchi-polytechnic'),
  ('Lagos State Polytechnic', 'Ikorodu', 'Lagos', 'NG', 'lagos-state-polytechnic'),
  ('Moshood Abiola Polytechnic', 'Abeokuta', 'Ogun', 'NG', 'moshood-abiola-polytechnic'),
  ('The Polytechnic, Ibadan', 'Ibadan', 'Oyo', 'NG', 'the-polytechnic-ibadan'),
  ('Kwara State Polytechnic', 'Ilorin', 'Kwara', 'NG', 'kwara-state-polytechnic'),
  ('Ken Saro-Wiwa Polytechnic', 'Bori', 'Rivers', 'NG', 'ken-saro-wiwa-polytechnic'),
  ('Lagos University Teaching Hospital', 'Idi-Araba', 'Lagos', 'NG', 'lagos-university-teaching-hospital'),
  ('Other — Lagos', 'Lagos', 'Lagos', 'NG', 'other-lagos'),
  ('Other — Abuja', 'Abuja', 'FCT', 'NG', 'other-abuja'),
  ('Other — Ibadan', 'Ibadan', 'Oyo', 'NG', 'other-ibadan'),
  ('Other — Kano', 'Kano', 'Kano', 'NG', 'other-kano'),
  ('Other — Port Harcourt', 'Port Harcourt', 'Rivers', 'NG', 'other-port-harcourt'),
  ('Other — Benin City', 'Benin City', 'Edo', 'NG', 'other-benin-city'),
  ('Other — Kaduna', 'Kaduna', 'Kaduna', 'NG', 'other-kaduna'),
  ('Other — Enugu', 'Enugu', 'Enugu', 'NG', 'other-enugu'),
  ('Other — Abeokuta', 'Abeokuta', 'Ogun', 'NG', 'other-abeokuta'),
  ('Other — Ilorin', 'Ilorin', 'Kwara', 'NG', 'other-ilorin'),
  ('Other — Jos', 'Jos', 'Plateau', 'NG', 'other-jos'),
  ('Other — Calabar', 'Calabar', 'Cross River', 'NG', 'other-calabar'),
  ('Other — Uyo', 'Uyo', 'Akwa Ibom', 'NG', 'other-uyo'),
  ('Other — Owerri', 'Owerri', 'Imo', 'NG', 'other-owerri'),
  ('Other — Warri', 'Warri', 'Delta', 'NG', 'other-warri'),
  ('Other — Onitsha', 'Onitsha', 'Anambra', 'NG', 'other-onitsha'),
  ('Other — Aba', 'Aba', 'Abia', 'NG', 'other-aba'),
  ('Other — Maiduguri', 'Maiduguri', 'Borno', 'NG', 'other-maiduguri'),
  ('Other — Sokoto', 'Sokoto', 'Sokoto', 'NG', 'other-sokoto'),
  ('Other — Akure', 'Akure', 'Ondo', 'NG', 'other-akure'),
  ('Other — Osogbo', 'Osogbo', 'Osun', 'NG', 'other-osogbo'),
  ('Other — Awka', 'Awka', 'Anambra', 'NG', 'other-awka'),
  ('Other — Asaba', 'Asaba', 'Delta', 'NG', 'other-asaba'),
  ('Other — Makurdi', 'Makurdi', 'Benue', 'NG', 'other-makurdi'),
  ('Other — Minna', 'Minna', 'Niger', 'NG', 'other-minna'),
  ('Other — Gombe', 'Gombe', 'Gombe', 'NG', 'other-gombe'),
  ('Other — Bauchi', 'Bauchi', 'Bauchi', 'NG', 'other-bauchi'),
  ('Other — Yenagoa', 'Yenagoa', 'Bayelsa', 'NG', 'other-yenagoa'),
  ('Other — Lokoja', 'Lokoja', 'Kogi', 'NG', 'other-lokoja'),
  ('Other — Jalingo', 'Jalingo', 'Taraba', 'NG', 'other-jalingo'),
  ('Other — Abakaliki', 'Abakaliki', 'Ebonyi', 'NG', 'other-abakaliki'),
  ('Other — Umuahia', 'Umuahia', 'Abia', 'NG', 'other-umuahia'),
  ('Other — Katsina', 'Katsina', 'Katsina', 'NG', 'other-katsina'),
  ('Other — Dutse', 'Dutse', 'Jigawa', 'NG', 'other-dutse'),
  ('Other — Damaturu', 'Damaturu', 'Yobe', 'NG', 'other-damaturu'),
  ('Other — Birnin Kebbi', 'Birnin Kebbi', 'Kebbi', 'NG', 'other-birnin-kebbi'),
  ('Other — Gusau', 'Gusau', 'Zamfara', 'NG', 'other-gusau'),
  ('Other — Lafia', 'Lafia', 'Nasarawa', 'NG', 'other-lafia'),
  ('Other — Yola', 'Yola', 'Adamawa', 'NG', 'other-yola'),
  ('Other (city in Nigeria)', 'Nigeria', 'Nigeria', 'NG', 'other-city-nigeria')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  country_code = EXCLUDED.country_code,
  active = TRUE;
