const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# [withFmtCxx17]';

/**
 * fmt 11.0.2 — pinned by react-native's third-party-podspecs and required
 * exactly by RCT-Folly, so it cannot simply be bumped — does not compile under
 * recent Xcode clang: its consteval format-string checks fail with
 * "call to consteval function ... is not a constant expression".
 *
 * fmt selects that path via FMT_USE_CONSTEVAL in base.h, and that block has no
 * user-override guard: it redefines the macro unconditionally, so passing
 * -DFMT_USE_CONSTEVAL=0 or -DFMT_CONSTEVAL= is ignored. The one gate it does
 * honour is the language standard:
 *
 *     #elif FMT_CPLUSPLUS < 201709L
 *     #  define FMT_USE_CONSTEVAL 0
 *
 * so building this one pod as C++17 turns consteval off at the source. Only
 * fmt's own translation units are affected; every other pod keeps C++20.
 *
 * This lives as a config plugin because ios/ is gitignored and regenerated by
 * `expo prebuild`, which would otherwise drop the fix.
 */
const POST_INSTALL = `
    ${MARKER} see plugins/withFmtCxx17.js
    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
`;

module.exports = function withFmtCxx17(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfile, 'utf8');
      if (contents.includes(MARKER)) return cfg;

      // Append inside the existing `post_install do |installer|` block.
      const anchor = '    react_native_post_install(';
      const close = contents.indexOf('    )', contents.indexOf(anchor));
      if (contents.indexOf(anchor) === -1 || close === -1) {
        throw new Error('[withFmtCxx17] could not find react_native_post_install in the Podfile');
      }
      const insertAt = close + '    )'.length;
      contents = contents.slice(0, insertAt) + '\n' + POST_INSTALL + contents.slice(insertAt);
      fs.writeFileSync(podfile, contents);
      return cfg;
    },
  ]);
};
