const { withAndroidManifest } = require('expo/config-plugins');

const READ_EXTERNAL_STORAGE = 'android.permission.READ_EXTERNAL_STORAGE';

/**
 * Bounds READ_EXTERNAL_STORAGE to Android 12 and below.
 *
 * Dependencies (expo-image-picker, expo-document-picker, the Fresco image
 * stack) declare this permission unbounded, so the merged manifest asks every
 * device for broad media access. From Android 13 the permission does nothing —
 * the system Photo Picker grants per-file access with no permission at all —
 * but Play reviewers still see a request for broad storage access and ask what
 * it is for. `android.permission.READ_MEDIA_*` is deliberately NOT added: the
 * Photo Picker covers every path this app uses.
 *
 * maxSdkVersion="32" rather than removal, because minSdkVersion is 24 and
 * picking an image on Android 7-12 does still need the permission — dropping it
 * outright would break photo notes, flashcard images, avatars and marketplace
 * listing uploads on those devices.
 *
 * This is a config plugin because android/ is gitignored and regenerated by
 * `expo prebuild`, which would otherwise drop the attribute. Sibling
 * permissions that are simply unnecessary (SYSTEM_ALERT_WINDOW, which leaks in
 * from react-native's debug manifest, and WRITE_EXTERNAL_STORAGE) are removed
 * via `android.blockedPermissions` in app.config.ts instead.
 */
module.exports = function withScopedStoragePermission(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    const permissions = manifest['uses-permission'];
    if (!Array.isArray(permissions)) return cfg;

    for (const permission of permissions) {
      if (permission?.$?.['android:name'] === READ_EXTERNAL_STORAGE) {
        permission.$['android:maxSdkVersion'] = '32';
      }
    }

    return cfg;
  });
};
